"""The generated activation backend: the cellular contraction model, stepped inside Newton.

:class:`GeneratedActivation` takes the ``mechanics`` component of a gotranx ``.ode``
file, generated as UFL by ``gotranx.cli.gotran2ufl`` (see
:func:`simcardemsx.ode_model.generate_ode_code`), and uses its generalized
Rush-Larsen step as the active stress of a ``pulse`` model.

With ``scheme="monolithic"`` (the default) ``S(C)`` takes one step of the
contraction model from the last converged states, with the fibre stretch and
stretch rate of the *current* displacement, and returns the resulting tension as
a stress. Newton therefore differentiates through the contraction model, as the
old :class:`~simcardemsx.backends.ZetaSplitUFL` did for the two distortion states
only -- here it is whatever the component contains, derived from the ``.ode`` file
rather than ported by hand.

``scheme="segregated"`` instead steps with the stretch and rate frozen at the last
converged step: the naive segregated scheme, kept as the comparison it is not
convergent against.

``scheme="stabilized"`` is Regazzoni & Quarteroni's (2021) stabilized segregated
scheme. It takes the segregated step and stores the same states, but adds the term of
their Eq. (19) to that step's tension: ``Ta + Ka (λ(u) - λ_n)``, with ``λ_n`` the
frozen stretch, through ``pulse.StabilizedActiveStress``. ``Ka`` is the UFL derivative
of the stepped tension with respect to the step's end stretch, taken at the frozen
point. It runs through both of that stretch's uses, the length dependence and the
stretch rate, so it includes the rate's ``1/dt``. It is the discrete counterpart of
their Eq. (44), which adds the length dependence to the rate path ``∂Ṫa/∂λ̇`` of
their Eq. (42). The term is O(dt), so the scheme stays consistent, and it keeps the
scheme stable where active stiffness exceeds passive. It is defined in the stretch
formulation only. ``tension_scale`` multiplies ``Ta`` and ``Ka`` alike, since scaling
one without the other would break the consistency of the stabilization.

``t``, ``dt`` and every parameter are ``dolfinx.fem.Constant``, read when the form
is assembled. That is not a detail: ``pulse`` compiles the form once, while
``dt == 0``, and ``ZetaSplitUFL`` branched on a Python-float ``dt`` while building
UFL, so its compiled form never saw the stretch rate. gotranx's UFL printer also
emits ``ufl.Or(x > a, x < b)``, which fails on a Python-float ``x``.

Under ``pulse.DynamicProblem``, which assembles the material form at the
generalized-alpha ``alpha_f`` point, this backend sets
:attr:`evaluate_at_end_of_step`: its ``Ta`` depends on states advanced *over* the
step, not on the instantaneous deformation, so ``S`` must instead see the true
end-of-step displacement -- ``C(u_{n+1})``, the same ``u`` :meth:`post_solve` then
compiles its own expressions against. ``pulse.StaticProblem`` has no ``alpha_f``
point to differ from, so the flag has no effect there.
"""

from __future__ import annotations

import logging
import types
from collections.abc import Mapping, Sequence
from typing import Any, Literal, NamedTuple

import basix.ufl
import dolfinx
import numpy as np
import pulse
import ufl

from ..averaging import make_averager

logger = logging.getLogger(__name__)

#: Factor converting a tension in the given unit to Pa, the stress unit of the mechanics.
TENSION_TO_PA: dict[str, float] = {"Pa": 1.0, "kPa": 1000.0}

#: Parameters of the component that the scheme computes from the displacement.
_KINEMATIC_PARAMETERS = ("lmbda", "dLambda")

#: Floor on ``dt`` in the stretch rate. The rate is selected away when ``dt == 0``, but
#: the generated code may evaluate both branches of a conditional, so it must be finite.
_DT_FLOOR = 1e-12


class _PostSolveExpressions(NamedTuple):
    """What ``post_solve`` evaluates, compiled once in ``register``."""

    states: dolfinx.fem.Expression
    lmbda: dolfinx.fem.Expression
    dLambda: dolfinx.fem.Expression | None  # only the frozen schemes store the rate
    tension_kPa: dolfinx.fem.Expression
    stiffness_kPa: dolfinx.fem.Expression
    outputs: dict[str, dolfinx.fem.Expression]


class GeneratedActivation(pulse.active_model.ActiveModel):
    """Active stress from one generalized Rush-Larsen step of a generated contraction model.

    Parameters
    ----------
    module:
        The ``mechanics`` module generated by ``gotranx.cli.gotran2ufl``, as loaded by
        :func:`simcardemsx.ode_model.load_ode_modules`. It must declare the parameters
        ``lmbda`` and ``dLambda``.
    mesh:
        The mechanics mesh.
    f0:
        Fibre direction (any UFL vector).
    quadrature_degree:
        Degree of the quadrature space the states live in by default. It must equal
        the quadrature degree of the mechanics form: FFCx evaluates an entire
        integral at a quadrature-element coefficient's own degree and ignores the
        measure's ``metadata={"quadrature_degree": ...}``, so a mismatch would
        silently change the quadrature of the whole momentum integral rather than
        just which states are looked up.
    element:
        A ``(family, degree)`` to store the states in instead of quadrature, e.g.
        ``("DG", 1)`` for comparison with physcardems.
    scheme:
        ``"monolithic"``: ``lmbda = λ(u)`` and ``dLambda = (λ(u) - lmbda_prev) / dt``, so
        Newton differentiates through the step. ``"segregated"``: ``lmbda`` and
        ``dLambda`` are frozen at the last converged step (the naive scheme).
        ``"stabilized"``: the segregated step, with Regazzoni & Quarteroni's Eq. (19)
        term ``Ka (λ(u) - λ_n)`` added to its tension, ``λ_n`` the frozen stretch.
        ``Ka`` is the derivative of the step's tension with respect to its end
        stretch, at the frozen point, and so includes the ``1/dt`` of the rate. It
        requires the ``stretch`` formulation, and ``tension_scale`` multiplies ``Ka``
        as well as ``Ta``.
    parameters:
        Overrides of the module's parameter values, by name. ``lmbda`` and ``dLambda``
        are computed by the scheme and cannot be overridden.
    tension:
        The monitor of the module that is the active tension.
    tension_unit:
        The unit of ``tension`` in the model; a key of :data:`TENSION_TO_PA`.
    formulation:
        ``stretch`` (the default, ADR 0001): ``S = Ta / λ f0 ⊗ f0``, so that
        ``|P f0| = Ta``. ``invariant``: ``S = Ta f0 ⊗ f0``, larger by a factor of λ,
        kept only to reproduce old results.
    tension_scale:
        Optional factor multiplying ``Ta``, applied in both ``S`` (before the
        unit conversion to Pa) and the ``tension`` expression :meth:`post_solve`
        averages into :attr:`active_tension`; under ``stabilized`` it multiplies
        ``Ka`` in ``S`` too. A per-cell ``dolfinx.fem.Function``
        (e.g. DG0) masks the active stress out of part of the domain -- 0 there,
        1 elsewhere -- without touching the states themselves; ``None`` (the
        default) leaves ``Ta`` unscaled.

    Attributes
    ----------
    evaluate_at_end_of_step:
        ``True`` (overriding :class:`pulse.active_model.ActiveModel`'s default):
        ``Ta`` depends on states advanced by one Rush-Larsen step using the
        stretch *rate* of the displacement, so ``pulse.DynamicProblem`` must
        assemble ``S`` at the true end-of-step displacement rather than at its
        usual ``alpha_f`` point. Has no effect under ``pulse.StaticProblem``.
    t, dt:
        Start and length of the current step, in ms. The controller sets both before
        each solve; ``dt`` starts at 0, for which the step is the identity.
    parameters:
        The module's parameters as Constants, by name (without ``lmbda``/``dLambda``).
    space:
        Scalar space of ``lmbda_prev``, ``inputs`` and ``outputs``.
    states_prev:
        Every state of the component at the last converged step, as one vector
        Function (component ``i`` is ``module.state`` index ``i``).
    lmbda_prev:
        Fibre stretch at the last converged step.
    inputs:
        One Function per name in ``module.missing``: what the component needs from EP.
        The controller writes into these.
    outputs:
        One Function per name in ``module.provides`` -- the module's ``missing_values``
        after the last step, i.e. what EP needs -- plus ``"lmbda"``.
    active_tension:
        ``tension`` after the last step, averaged onto P1 on ``mesh``, **in kPa**
        whatever ``tension_unit`` is. (``ZetaSplitUFL`` reports Pa and
        ``CrossbridgeSegregated`` kPa.)
    tension_kPa:
        The same tension before that average, on :attr:`space` (read-only).
    """

    evaluate_at_end_of_step = True

    def __init__(
        self,
        module: types.ModuleType,
        mesh: dolfinx.mesh.Mesh,
        f0,
        *,
        quadrature_degree: int,
        element: tuple[str, int] | None = None,
        scheme: Literal["monolithic", "segregated", "stabilized"] = "monolithic",
        parameters: Mapping[str, float] | None = None,
        tension: str = "Ta",
        tension_unit: str = "kPa",
        formulation: pulse.ActiveStressFormulation = pulse.ActiveStressFormulation.stretch,
        tension_scale: dolfinx.fem.Function | ufl.core.expr.Expr | None = None,
    ):
        if scheme not in ("monolithic", "segregated", "stabilized"):
            raise ValueError(
                f"scheme must be 'monolithic', 'segregated' or 'stabilized', got {scheme!r}",
            )
        if (
            scheme == "stabilized"
            and pulse.ActiveStressFormulation(formulation) != pulse.ActiveStressFormulation.stretch
        ):
            raise ValueError(
                "scheme='stabilized' requires formulation='stretch': Regazzoni & "
                "Quarteroni's Eq. (19) is derived in the stretch formulation, and "
                "pulse.StabilizedActiveStress implements only that.",
            )
        if tension not in module.monitor:
            raise KeyError(
                f"tension {tension!r} is not a monitor of the module. "
                f"Available: {sorted(module.monitor)}",
            )
        if tension_unit not in TENSION_TO_PA:
            raise ValueError(
                f"Unknown tension_unit {tension_unit!r}. Known: {sorted(TENSION_TO_PA)}",
            )
        missing_kinematic = [p for p in _KINEMATIC_PARAMETERS if p not in module.parameter]
        if missing_kinematic:
            raise KeyError(
                f"The mechanics component must declare the parameters {missing_kinematic}; "
                "the scheme supplies them from the displacement.",
            )

        self.module = module
        self.mesh = mesh
        self.f0 = f0
        self.quadrature_degree = quadrature_degree
        self.scheme = scheme
        self.formulation = pulse.ActiveStressFormulation(formulation)
        self.tension = tension
        self.tension_unit = tension_unit
        self.tension_scale = tension_scale
        self._tension_index = module.monitor[tension]
        self._to_Pa = TENSION_TO_PA[tension_unit]

        self.t = dolfinx.fem.Constant(mesh, dolfinx.default_scalar_type(0.0))
        self.dt = dolfinx.fem.Constant(mesh, dolfinx.default_scalar_type(0.0))
        self._parameter_constants = self._make_parameters(parameters or {})
        self.parameters = {
            name: self._parameter_constants[index]
            for name, index in module.parameter.items()
            if name not in _KINEMATIC_PARAMETERS
        }

        num_states = len(module.state)
        if element is None:
            cell = mesh.basix_cell()
            self.space = dolfinx.fem.functionspace(
                mesh,
                basix.ufl.quadrature_element(cell, value_shape=(), degree=quadrature_degree),
            )
            states_space = dolfinx.fem.functionspace(
                mesh,
                basix.ufl.quadrature_element(
                    cell,
                    value_shape=(num_states,),
                    degree=quadrature_degree,
                ),
            )
        else:
            family, degree = element
            self.space = dolfinx.fem.functionspace(mesh, (family, degree))
            states_space = dolfinx.fem.functionspace(mesh, (family, degree, (num_states,)))

        self.states_prev = dolfinx.fem.Function(states_space, name="states_prev")
        self.states_prev.x.array.reshape(-1, num_states)[:] = module.init_state_values()
        #: The module's state names, in the order of ``states_prev``'s components.
        self._state_names = sorted(module.state, key=module.state.__getitem__)
        self._states_next = dolfinx.fem.Function(states_space)

        self.lmbda_prev = dolfinx.fem.Function(self.space, name="lmbda_prev")
        self.lmbda_prev.x.array[:] = 1.0

        missing = getattr(module, "missing", {})
        self.inputs = {name: dolfinx.fem.Function(self.space, name=name) for name in missing}
        # In the module's order, so that missing_variables[i] is the input at index i.
        self._missing = [self.inputs[name] for name in sorted(missing, key=missing.__getitem__)]
        self.outputs = {
            name: dolfinx.fem.Function(self.space, name=name)
            for name in (*module.provides, "lmbda")
        }

        # The frozen schemes' lmbda and dLambda, fixed at the last converged step.
        self._lmbda_frozen = dolfinx.fem.Function(self.space)
        self._lmbda_frozen.x.array[:] = 1.0
        self._dLambda_frozen = dolfinx.fem.Function(self.space)
        self._dLambda_next = dolfinx.fem.Function(self.space)

        self._tension_kPa = dolfinx.fem.Function(self.space)
        self.active_tension = dolfinx.fem.Function(
            dolfinx.fem.functionspace(mesh, ("P", 1)),
            name="active_tension",
        )
        self._stiffness_kPa = dolfinx.fem.Function(self.space)
        self._average_tension = make_averager(self._tension_kPa, self.active_tension)

        self.u: dolfinx.fem.Function | None = None
        self._post_solve_expressions: _PostSolveExpressions | None = None

        # Regazzoni & Quarteroni's Eq. (19) on the segregated step: pulse's stress, with
        # Ta and Ka taken at the frozen point, where the ODE is advanced.
        self._stabilized: pulse.StabilizedActiveStress | None = None
        if scheme == "stabilized":
            Ta, Ka = self._step_tension_and_stiffness(
                self._lmbda_frozen,
                self._dLambda_frozen,
                self._lmbda_frozen,
            )
            if tension_scale is not None:
                Ta, Ka = tension_scale * Ta, tension_scale * Ka
            self._stabilized = pulse.StabilizedActiveStress(
                f0=f0,
                activation=pulse.Variable(Ta, tension_unit),
                active_stiffness=pulse.Variable(Ka, tension_unit),
                lmbda_prev=self._lmbda_frozen,
            )

    @property
    def tension_kPa(self) -> dolfinx.fem.Function:
        """``tension`` after the last step, in kPa, at the backend's own points.

        The ``Function`` on :attr:`space` (quadrature by default) that :meth:`post_solve`
        writes and :attr:`active_tension` is averaged from, with ``tension_scale``
        applied. It is not averaged: where ``tension_scale`` is 0 it is exactly 0,
        whereas ``active_tension``'s P1 average blends masked and unmasked cells at
        the nodes they share. Each ``post_solve`` overwrites it in place.

        Under ``stabilized`` it is the tension ``Ta_seg`` of the stored states, the
        monitor of the step, and not ``Ta_seg + Ka Δλ``, the stress the residual saw.
        """
        return self._tension_kPa

    @property
    def stiffness_kPa(self) -> dolfinx.fem.Function:
        """``Ka = dTa/dλ`` of the last accepted step, in kPa per unit stretch.

        The ``Function`` on :attr:`space` that :meth:`post_solve` writes in place, with
        ``tension_scale`` applied, so it is exactly 0 where the mask is 0. ``Ka`` is
        the derivative of the stepped tension through both the length dependence and
        the stretch rate (its ``1/dt``), taken at the step's evaluation point, for
        every scheme:

        - ``monolithic``: the converged λ(u), with the rate measured from ``lmbda_prev``,
          the λ of the step before;
        - ``segregated`` and ``stabilized``: the frozen point (λ_n, and the rate of the
          step before), which is the ``Ka`` the stabilized residual used.
        """
        return self._stiffness_kPa

    def _make_parameters(self, overrides: Mapping[str, float]) -> list[dolfinx.fem.Constant]:
        """One Constant per entry of ``init_parameter_values()``, with ``overrides`` applied.

        Per *index*, not per name: gotranx can emit a parameter twice (the first a dead
        read), so there can be more entries than names.
        """
        names = self.module.parameter
        available = sorted(name for name in names if name not in _KINEMATIC_PARAMETERS)
        for name in overrides:
            if name in _KINEMATIC_PARAMETERS:
                raise KeyError(
                    f"{name!r} cannot be overridden: the scheme computes lmbda and dLambda "
                    f"from the displacement. Available: {available}",
                )
            if name not in names:
                raise KeyError(f"Unknown parameter {name!r}. Available: {available}")

        constants = [
            dolfinx.fem.Constant(self.mesh, dolfinx.default_scalar_type(value))
            for value in self.module.init_parameter_values()
        ]
        for name, value in overrides.items():
            constants[names[name]].value = value
        return constants

    # ------------------------------------------------------------------
    # The step
    # ------------------------------------------------------------------

    def _rate(self, lmbda: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        """``(lmbda - lmbda_prev) / dt``, and 0 when ``dt == 0``."""
        return ufl.conditional(
            ufl.gt(self.dt, 0.0),
            (lmbda - self.lmbda_prev) / ufl.max_value(self.dt, _DT_FLOOR),
            0.0,
        )

    def _parameter_list(self, lmbda: ufl.core.expr.Expr) -> list[Any]:
        """The module's parameter list, with ``lmbda``/``dLambda`` supplied by the scheme."""
        p: list[Any] = list(self._parameter_constants)
        if self.scheme == "monolithic":
            p[self.module.parameter["lmbda"]] = lmbda
            p[self.module.parameter["dLambda"]] = self._rate(lmbda)
        else:
            p[self.module.parameter["lmbda"]] = self._lmbda_frozen
            p[self.module.parameter["dLambda"]] = self._dLambda_frozen
        return p

    def _step(self, lmbda: ufl.core.expr.Expr) -> tuple[list[Any], list[Any]]:
        """New states after one GRL step from ``states_prev``, and the parameters used."""
        p = self._parameter_list(lmbda)
        states = [self.states_prev[i] for i in range(len(self.module.state))]
        new = self.module.generalized_rush_larsen(states, self.t, self.dt, p, self._missing)
        return new, p

    def _step_tension_and_stiffness(
        self,
        lmbda_end: ufl.core.expr.Expr,
        rate_base: ufl.core.expr.Expr | float,
        lmbda_base: ufl.core.expr.Expr,
    ) -> tuple[ufl.core.expr.Expr, ufl.core.expr.Expr]:
        """``tension`` after one GRL step from ``states_prev``, and its derivative ``Ka``.

        The step's ``lmbda`` is ``ℓ = lmbda_end`` and its ``dLambda`` is
        ``rate_base + (ℓ - lmbda_base) / dt``, the increment guarded like
        :meth:`_rate` (0 when ``dt == 0``). ``Ka`` is ``ufl.diff`` of the tension with
        respect to ``ℓ``, through both of its uses: the length dependence, and the
        rate, with its ``1/dt``. Both are in ``tension_unit`` (``Ka`` per unit
        stretch), without ``tension_scale``.
        """
        lmbda = ufl.variable(lmbda_end)
        p: list[Any] = list(self._parameter_constants)
        p[self.module.parameter["lmbda"]] = lmbda
        p[self.module.parameter["dLambda"]] = rate_base + ufl.conditional(
            ufl.gt(self.dt, 0.0),
            (lmbda - lmbda_base) / ufl.max_value(self.dt, _DT_FLOOR),
            0.0,
        )
        states = [self.states_prev[i] for i in range(len(self.module.state))]
        new = self.module.generalized_rush_larsen(states, self.t, self.dt, p, self._missing)
        tension = self.module.monitor_values(self.t, new, p, self._missing)[self._tension_index]
        return tension, ufl.diff(tension, lmbda)

    def _fibre_stretch(self, C: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        return ufl.sqrt(ufl.inner(C * self.f0, self.f0))

    # ------------------------------------------------------------------
    # pulse.ActiveModel
    # ------------------------------------------------------------------

    @property
    def missing(self) -> Mapping[str, int]:
        """What the activation module needs from EP, name -> index."""
        return getattr(self.module, "missing", {})

    @property
    def provides(self) -> Mapping[str, int]:
        """What the activation module hands to EP, name -> index."""
        return self.module.provides

    def begin_step(self, t_n: float, dt: float) -> None:
        """Set the step's start time and length (ms), read when the form is assembled."""
        self.t.value = np.asarray(t_n)
        self.dt.value = np.asarray(dt)

    def register(self, u: dolfinx.fem.Function) -> None:
        """Receive the displacement (``pulse.StaticProblem`` calls this) and compile
        what :meth:`post_solve` evaluates."""
        self.u = u
        F = ufl.grad(u) + ufl.Identity(self.mesh.geometry.dim)
        lmbda = self._fibre_stretch(F.T * F)
        new, p = self._step(lmbda)

        # Ta and the outputs are evaluated on the stored new states rather than on the
        # step expression, which keeps their kernels small. The values are the same.
        stored = [self._states_next[i] for i in range(len(self.module.state))]
        tension = self.module.monitor_values(self.t, stored, p, self._missing)[self._tension_index]
        if self.tension_scale is not None:
            tension = self.tension_scale * tension
        provided = self.module.missing_values(self.t, stored, p, self._missing)

        if self.scheme == "monolithic":
            _, Ka = self._step_tension_and_stiffness(lmbda, 0.0, self.lmbda_prev)
        else:
            _, Ka = self._step_tension_and_stiffness(
                self._lmbda_frozen,
                self._dLambda_frozen,
                self._lmbda_frozen,
            )
        if self.tension_scale is not None:
            Ka = self.tension_scale * Ka

        points = self.space.element.interpolation_points
        self._post_solve_expressions = _PostSolveExpressions(
            states=dolfinx.fem.Expression(
                ufl.as_vector(new),
                self.states_prev.function_space.element.interpolation_points,
            ),
            lmbda=dolfinx.fem.Expression(lmbda, points),
            dLambda=(
                dolfinx.fem.Expression(self._rate(lmbda), points)
                if self.scheme != "monolithic"
                else None
            ),
            tension_kPa=dolfinx.fem.Expression(tension * (self._to_Pa / 1000.0), points),
            stiffness_kPa=dolfinx.fem.Expression(Ka * (self._to_Pa / 1000.0), points),
            outputs={
                name: dolfinx.fem.Expression(provided[index], points)
                for name, index in self.module.provides.items()
            },
        )

    def Fe(self, F: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        return F

    def strain_energy(self, C: ufl.core.expr.Expr):
        """Not available for this backend (ADR 0003).

        ``Ta`` depends on the stretch through states that depend on the stretch
        *rate*, so there is no closed-form potential to differentiate. ``S`` is
        supplied directly, which is all ``pulse.StaticProblem`` assembles.
        """
        raise NotImplementedError(
            "GeneratedActivation has no active strain-energy potential; it supplies S "
            "directly. pulse.StaticProblem assembles model.S(C), so this is not needed.",
        )

    def S(self, C: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        """Active second Piola-Kirchhoff stress, in Pa, after one step at the stretch of ``C``.

        Under ``stabilized`` it is the ``pulse.StabilizedActiveStress`` built in
        ``__init__``, whose ``Ta`` and ``Ka`` come from the segregated step.
        """
        if self._stabilized is not None:
            return self._stabilized.S(C)
        lmbda = self._fibre_stretch(C)
        new, p = self._step(lmbda)
        Ta = self.module.monitor_values(self.t, new, p, self._missing)[self._tension_index]
        if self.tension_scale is not None:
            Ta = self.tension_scale * Ta
        Ta_Pa = self._to_Pa * Ta
        if self.formulation == pulse.ActiveStressFormulation.stretch:
            Ta_Pa = Ta_Pa / lmbda
        return Ta_Pa * ufl.outer(self.f0, self.f0)

    def P(self, F: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        return F * self.S(F.T * F)

    # ------------------------------------------------------------------
    # After a converged solve
    # ------------------------------------------------------------------

    def reset_stretch(self) -> None:
        """Take λ(u) of the registered displacement as the stretch at rest.

        For a problem that starts deformed. ``lmbda_prev``, the frozen ``lmbda`` and
        ``outputs["lmbda"]`` are set to λ(u), and the frozen ``dLambda`` to 0, so the
        first step sees no stretch rate under any scheme. The states are untouched and
        nothing is sent to EP: the caller then calls ``controller.plan.backward()``.

        The other way to start deformed is one accepted solve at ``dt == 0``, where the
        step is the identity.
        """
        expressions = self._post_solve_expressions
        if expressions is None:
            raise RuntimeError("register(u) must be called before reset_stretch()")

        self.outputs["lmbda"].interpolate(expressions.lmbda)
        lmbda = self.outputs["lmbda"].x.array
        self.lmbda_prev.x.array[:] = lmbda
        self._lmbda_frozen.x.array[:] = lmbda
        self._dLambda_frozen.x.array[:] = 0.0

    def post_solve(self) -> None:
        """Accept the step taken with the converged displacement.

        Stores the states of the step the residual used, and λ(u), as the new
        previous values; for ``segregated`` and ``stabilized`` also refreshes the frozen
        ``lmbda`` and ``dLambda``; refreshes ``outputs`` and ``active_tension``.

        Everything is evaluated before anything is overwritten: the step reads
        ``states_prev``, and ``lmbda_prev`` (monolithic) or the frozen pair
        (segregated, stabilized).

        At ``dt == 0`` the step is the identity, so a ``post_solve()`` then accepts the
        current ``u`` as the rest state: the states are kept and ``lmbda_prev := λ(u)``.
        """
        expressions = self._post_solve_expressions
        if expressions is None:
            raise RuntimeError("register(u) must be called before post_solve()")

        self._states_next.interpolate(expressions.states)
        self.outputs["lmbda"].interpolate(expressions.lmbda)
        if expressions.dLambda is not None:
            self._dLambda_next.interpolate(expressions.dLambda)
        self._tension_kPa.interpolate(expressions.tension_kPa)
        self._stiffness_kPa.interpolate(expressions.stiffness_kPa)
        for name, expression in expressions.outputs.items():
            self.outputs[name].interpolate(expression)

        lmbda = self.outputs["lmbda"].x.array
        self.states_prev.x.array[:] = self._states_next.x.array
        self.lmbda_prev.x.array[:] = lmbda
        if self.scheme != "monolithic":
            self._lmbda_frozen.x.array[:] = lmbda
            self._dLambda_frozen.x.array[:] = self._dLambda_next.x.array

        self._average_tension()

    # ------------------------------------------------------------------
    # Checkpoint / restart (simcardemsx.checkpoint.Checkpointable)
    # ------------------------------------------------------------------

    namespace = "activation"

    @property
    def step_pending(self) -> bool:
        """Always ``False``: ``begin_step`` only sets ``t`` and ``dt``, and nothing is
        half-accepted between it and :meth:`post_solve`."""
        return False

    def restart_functions(self) -> list[tuple[str, dolfinx.fem.Function]]:
        """The backend's own Functions that carry the accepted state."""
        return [
            ("activation_states_prev", self.states_prev),
            ("activation_lmbda_prev", self.lmbda_prev),
            ("activation_lmbda_frozen", self._lmbda_frozen),
            ("activation_dLambda_frozen", self._dLambda_frozen),
            ("activation_tension_kPa", self._tension_kPa),
            ("activation_stiffness_kPa", self._stiffness_kPa),
            *((f"activation_output_{name}", self.outputs[name]) for name in sorted(self.outputs)),
        ]

    def restart_metadata(self) -> dict[str, Any]:
        """The kind (backend and scheme), and ``state_names``: the module's state
        names in the order of ``states_prev``'s components."""
        return {
            "backend": "GeneratedActivation",
            "scheme": self.scheme,
            "state_names": list(self._state_names),
        }

    def load_restart(
        self,
        functions: Sequence[tuple[str, dolfinx.fem.Function]],
        metadata: Mapping[str, Any],
    ) -> None:
        """Check the metadata, put ``states_prev``'s components into this module's
        order, and re-average ``active_tension``.

        The Functions in ``functions`` are the backend's own, already filled by the
        caller, so ``states_prev`` holds the components in the saved order. gotranx may
        order a module's states differently in another process, so the saved
        ``state_names`` are mapped onto this module's by name. Every other Function is
        one name's own.

        Raises ``ValueError`` if the backend or the scheme differ, or if the saved
        state names are not this module's (in any order).
        """
        kind = {key: metadata.get(key) for key in ("backend", "scheme")}
        own_kind = {"backend": "GeneratedActivation", "scheme": self.scheme}
        if kind != own_kind:
            raise ValueError(
                f"Checkpoint was written by {dict(metadata)}, "
                f"this backend is {self.restart_metadata()} (scheme must match)",
            )
        saved, own = list(metadata.get("state_names", [])), self._state_names
        if sorted(saved) != sorted(own):
            raise ValueError(
                f"The checkpoint's activation states are {saved}, this module's are {own}",
            )
        if saved != own:
            components = self.states_prev.x.array.reshape(-1, len(own))
            components[:] = components[:, [saved.index(name) for name in own]]
        self._average_tension()
