"""The generated activation backend: the cellular contraction model, stepped inside Newton.

:class:`GeneratedActivation` takes the ``mechanics`` component of a gotranx ``.ode``
file, generated as UFL by ``gotranx.cli.gotran2ufl`` (see
:func:`simcardemsx.ode_model.generate_ode_code`), and uses its generalized
Rush-Larsen step as the active stress of a ``pulse`` model.

With ``scheme="monolithic"`` (the default) ``S(C)`` takes one step of the
contraction model from the last converged states, with the fibre stretch and
stretch rate of the *current* displacement, and returns the resulting tension as
a stress. Newton therefore differentiates through the contraction model, as the
old :class:`~simcardemsx.backends.ZetaSplitUFL` did for the two distortion states
only -- here it is whatever the component contains, derived from the ``.ode`` file
rather than ported by hand.

``scheme="segregated"`` instead steps with the stretch and rate frozen at the last
converged step: the naive segregated scheme, kept as the comparison it is not
convergent against.

``t``, ``dt`` and every parameter are ``dolfinx.fem.Constant``, read when the form
is assembled. That is not a detail: ``pulse`` compiles the form once, while
``dt == 0``, and ``ZetaSplitUFL`` branched on a Python-float ``dt`` while building
UFL, so its compiled form never saw the stretch rate. gotranx's UFL printer also
emits ``ufl.Or(x > a, x < b)``, which fails on a Python-float ``x``.

Under ``pulse.DynamicProblem``, which assembles the material form at the
generalized-alpha ``alpha_f`` point, this backend sets
:attr:`evaluate_at_end_of_step`: its ``Ta`` depends on states advanced *over* the
step, not on the instantaneous deformation, so ``S`` must instead see the true
end-of-step displacement -- ``C(u_{n+1})``, the same ``u`` :meth:`post_solve` then
compiles its own expressions against. ``pulse.StaticProblem`` has no ``alpha_f``
point to differ from, so the flag has no effect there.
"""

from __future__ import annotations

import logging
import types
from collections.abc import Mapping
from typing import Any, Literal, NamedTuple

import basix.ufl
import dolfinx
import pulse
import ufl

from ..averaging import make_averager

logger = logging.getLogger(__name__)

#: Factor converting a tension in the given unit to Pa, the stress unit of the mechanics.
TENSION_TO_PA: dict[str, float] = {"Pa": 1.0, "kPa": 1000.0}

#: Parameters of the component that the scheme computes from the displacement.
_KINEMATIC_PARAMETERS = ("lmbda", "dLambda")

#: Floor on ``dt`` in the stretch rate. The rate is selected away when ``dt == 0``, but
#: the generated code may evaluate both branches of a conditional, so it must be finite.
_DT_FLOOR = 1e-12


class _PostSolveExpressions(NamedTuple):
    """What ``post_solve`` evaluates, compiled once in ``register``."""

    states: dolfinx.fem.Expression
    lmbda: dolfinx.fem.Expression
    dLambda: dolfinx.fem.Expression | None  # only the segregated scheme stores the rate
    tension_kPa: dolfinx.fem.Expression
    outputs: dict[str, dolfinx.fem.Expression]


class GeneratedActivation(pulse.active_model.ActiveModel):
    """Active stress from one generalized Rush-Larsen step of a generated contraction model.

    Parameters
    ----------
    module:
        The ``mechanics`` module generated by ``gotranx.cli.gotran2ufl``, as loaded by
        :func:`simcardemsx.ode_model.load_ode_modules`. It must declare the parameters
        ``lmbda`` and ``dLambda``.
    mesh:
        The mechanics mesh.
    f0:
        Fibre direction (any UFL vector).
    quadrature_degree:
        Degree of the quadrature space the states live in by default. It must equal
        the quadrature degree of the mechanics form: FFCx evaluates an entire
        integral at a quadrature-element coefficient's own degree and ignores the
        measure's ``metadata={"quadrature_degree": ...}``, so a mismatch would
        silently change the quadrature of the whole momentum integral rather than
        just which states are looked up.
    element:
        A ``(family, degree)`` to store the states in instead of quadrature, e.g.
        ``("DG", 1)`` for comparison with physcardems.
    scheme:
        ``"monolithic"``: ``lmbda = λ(u)`` and ``dLambda = (λ(u) - lmbda_prev) / dt``, so
        Newton differentiates through the step. ``"segregated"``: ``lmbda`` and
        ``dLambda`` are frozen at the last converged step (the naive scheme).
    parameters:
        Overrides of the module's parameter values, by name. ``lmbda`` and ``dLambda``
        are computed by the scheme and cannot be overridden.
    tension:
        The monitor of the module that is the active tension.
    tension_unit:
        The unit of ``tension`` in the model; a key of :data:`TENSION_TO_PA`.
    formulation:
        ``stretch`` (the default, ADR 0001): ``S = Ta / λ f0 ⊗ f0``, so that
        ``|P f0| = Ta``. ``invariant``: ``S = Ta f0 ⊗ f0``, larger by a factor of λ,
        kept only to reproduce old results.
    tension_scale:
        Optional factor multiplying ``Ta``, applied in both ``S`` (before the
        unit conversion to Pa) and the ``tension`` expression :meth:`post_solve`
        averages into :attr:`active_tension`. A per-cell ``dolfinx.fem.Function``
        (e.g. DG0) masks the active stress out of part of the domain -- 0 there,
        1 elsewhere -- without touching the states themselves; ``None`` (the
        default) leaves ``Ta`` unscaled.

    Attributes
    ----------
    evaluate_at_end_of_step:
        ``True`` (overriding :class:`pulse.active_model.ActiveModel`'s default):
        ``Ta`` depends on states advanced by one Rush-Larsen step using the
        stretch *rate* of the displacement, so ``pulse.DynamicProblem`` must
        assemble ``S`` at the true end-of-step displacement rather than at its
        usual ``alpha_f`` point. Has no effect under ``pulse.StaticProblem``.
    t, dt:
        Start and length of the current step, in ms. The controller sets both before
        each solve; ``dt`` starts at 0, for which the step is the identity.
    parameters:
        The module's parameters as Constants, by name (without ``lmbda``/``dLambda``).
    space:
        Scalar space of ``lmbda_prev``, ``inputs`` and ``outputs``.
    states_prev:
        Every state of the component at the last converged step, as one vector
        Function (component ``i`` is ``module.state`` index ``i``).
    lmbda_prev:
        Fibre stretch at the last converged step.
    inputs:
        One Function per name in ``module.missing``: what the component needs from EP.
        The controller writes into these.
    outputs:
        One Function per name in ``module.provides`` -- the module's ``missing_values``
        after the last step, i.e. what EP needs -- plus ``"lmbda"``.
    active_tension:
        ``tension`` after the last step, averaged onto P1 on ``mesh``, **in kPa**
        whatever ``tension_unit`` is. (``ZetaSplitUFL`` reports Pa and
        ``CrossbridgeSegregated`` kPa.)
    """

    evaluate_at_end_of_step = True

    def __init__(
        self,
        module: types.ModuleType,
        mesh: dolfinx.mesh.Mesh,
        f0,
        *,
        quadrature_degree: int,
        element: tuple[str, int] | None = None,
        scheme: Literal["monolithic", "segregated"] = "monolithic",
        parameters: Mapping[str, float] | None = None,
        tension: str = "Ta",
        tension_unit: str = "kPa",
        formulation: pulse.ActiveStressFormulation = pulse.ActiveStressFormulation.stretch,
        tension_scale: dolfinx.fem.Function | ufl.core.expr.Expr | None = None,
    ):
        if scheme not in ("monolithic", "segregated"):
            raise ValueError(f"scheme must be 'monolithic' or 'segregated', got {scheme!r}")
        if tension not in module.monitor:
            raise KeyError(
                f"tension {tension!r} is not a monitor of the module. "
                f"Available: {sorted(module.monitor)}",
            )
        if tension_unit not in TENSION_TO_PA:
            raise ValueError(
                f"Unknown tension_unit {tension_unit!r}. Known: {sorted(TENSION_TO_PA)}",
            )
        missing_kinematic = [p for p in _KINEMATIC_PARAMETERS if p not in module.parameter]
        if missing_kinematic:
            raise KeyError(
                f"The mechanics component must declare the parameters {missing_kinematic}; "
                "the scheme supplies them from the displacement.",
            )

        self.module = module
        self.mesh = mesh
        self.f0 = f0
        self.quadrature_degree = quadrature_degree
        self.scheme = scheme
        self.formulation = pulse.ActiveStressFormulation(formulation)
        self.tension = tension
        self.tension_unit = tension_unit
        self.tension_scale = tension_scale
        self._tension_index = module.monitor[tension]
        self._to_Pa = TENSION_TO_PA[tension_unit]

        self.t = dolfinx.fem.Constant(mesh, dolfinx.default_scalar_type(0.0))
        self.dt = dolfinx.fem.Constant(mesh, dolfinx.default_scalar_type(0.0))
        self._parameter_constants = self._make_parameters(parameters or {})
        self.parameters = {
            name: self._parameter_constants[index]
            for name, index in module.parameter.items()
            if name not in _KINEMATIC_PARAMETERS
        }

        num_states = len(module.state)
        if element is None:
            cell = mesh.basix_cell()
            self.space = dolfinx.fem.functionspace(
                mesh,
                basix.ufl.quadrature_element(cell, value_shape=(), degree=quadrature_degree),
            )
            states_space = dolfinx.fem.functionspace(
                mesh,
                basix.ufl.quadrature_element(
                    cell,
                    value_shape=(num_states,),
                    degree=quadrature_degree,
                ),
            )
        else:
            family, degree = element
            self.space = dolfinx.fem.functionspace(mesh, (family, degree))
            states_space = dolfinx.fem.functionspace(mesh, (family, degree, (num_states,)))

        self.states_prev = dolfinx.fem.Function(states_space, name="states_prev")
        self.states_prev.x.array.reshape(-1, num_states)[:] = module.init_state_values()
        self._states_next = dolfinx.fem.Function(states_space)

        self.lmbda_prev = dolfinx.fem.Function(self.space, name="lmbda_prev")
        self.lmbda_prev.x.array[:] = 1.0

        missing = getattr(module, "missing", {})
        self.inputs = {name: dolfinx.fem.Function(self.space, name=name) for name in missing}
        # In the module's order, so that missing_variables[i] is the input at index i.
        self._missing = [self.inputs[name] for name in sorted(missing, key=missing.__getitem__)]
        self.outputs = {
            name: dolfinx.fem.Function(self.space, name=name)
            for name in (*module.provides, "lmbda")
        }

        # The segregated scheme's lmbda and dLambda, frozen at the last converged step.
        self._lmbda_frozen = dolfinx.fem.Function(self.space)
        self._lmbda_frozen.x.array[:] = 1.0
        self._dLambda_frozen = dolfinx.fem.Function(self.space)
        self._dLambda_next = dolfinx.fem.Function(self.space)

        self._tension_kPa = dolfinx.fem.Function(self.space)
        self.active_tension = dolfinx.fem.Function(
            dolfinx.fem.functionspace(mesh, ("P", 1)),
            name="active_tension",
        )
        self._average_tension = make_averager(self._tension_kPa, self.active_tension)

        self.u: dolfinx.fem.Function | None = None
        self._post_solve_expressions: _PostSolveExpressions | None = None

    def _make_parameters(self, overrides: Mapping[str, float]) -> list[dolfinx.fem.Constant]:
        """One Constant per entry of ``init_parameter_values()``, with ``overrides`` applied.

        Per *index*, not per name: gotranx can emit a parameter twice (the first a dead
        read), so there can be more entries than names.
        """
        names = self.module.parameter
        available = sorted(name for name in names if name not in _KINEMATIC_PARAMETERS)
        for name in overrides:
            if name in _KINEMATIC_PARAMETERS:
                raise KeyError(
                    f"{name!r} cannot be overridden: the scheme computes lmbda and dLambda "
                    f"from the displacement. Available: {available}",
                )
            if name not in names:
                raise KeyError(f"Unknown parameter {name!r}. Available: {available}")

        constants = [
            dolfinx.fem.Constant(self.mesh, dolfinx.default_scalar_type(value))
            for value in self.module.init_parameter_values()
        ]
        for name, value in overrides.items():
            constants[names[name]].value = value
        return constants

    # ------------------------------------------------------------------
    # The step
    # ------------------------------------------------------------------

    def _rate(self, lmbda: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        """``(lmbda - lmbda_prev) / dt``, and 0 when ``dt == 0``."""
        return ufl.conditional(
            ufl.gt(self.dt, 0.0),
            (lmbda - self.lmbda_prev) / ufl.max_value(self.dt, _DT_FLOOR),
            0.0,
        )

    def _parameter_list(self, lmbda: ufl.core.expr.Expr) -> list[Any]:
        """The module's parameter list, with ``lmbda``/``dLambda`` supplied by the scheme."""
        p: list[Any] = list(self._parameter_constants)
        if self.scheme == "monolithic":
            p[self.module.parameter["lmbda"]] = lmbda
            p[self.module.parameter["dLambda"]] = self._rate(lmbda)
        else:
            p[self.module.parameter["lmbda"]] = self._lmbda_frozen
            p[self.module.parameter["dLambda"]] = self._dLambda_frozen
        return p

    def _step(self, lmbda: ufl.core.expr.Expr) -> tuple[list[Any], list[Any]]:
        """New states after one GRL step from ``states_prev``, and the parameters used."""
        p = self._parameter_list(lmbda)
        states = [self.states_prev[i] for i in range(len(self.module.state))]
        new = self.module.generalized_rush_larsen(states, self.t, self.dt, p, self._missing)
        return new, p

    def _fibre_stretch(self, C: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        return ufl.sqrt(ufl.inner(C * self.f0, self.f0))

    # ------------------------------------------------------------------
    # pulse.ActiveModel
    # ------------------------------------------------------------------

    def register(self, u: dolfinx.fem.Function) -> None:
        """Receive the displacement (``pulse.StaticProblem`` calls this) and compile
        what :meth:`post_solve` evaluates."""
        self.u = u
        F = ufl.grad(u) + ufl.Identity(self.mesh.geometry.dim)
        lmbda = self._fibre_stretch(F.T * F)
        new, p = self._step(lmbda)

        # Ta and the outputs are evaluated on the stored new states rather than on the
        # step expression, which keeps their kernels small. The values are the same.
        stored = [self._states_next[i] for i in range(len(self.module.state))]
        tension = self.module.monitor_values(self.t, stored, p, self._missing)[self._tension_index]
        if self.tension_scale is not None:
            tension = self.tension_scale * tension
        provided = self.module.missing_values(self.t, stored, p, self._missing)

        points = self.space.element.interpolation_points
        self._post_solve_expressions = _PostSolveExpressions(
            states=dolfinx.fem.Expression(
                ufl.as_vector(new),
                self.states_prev.function_space.element.interpolation_points,
            ),
            lmbda=dolfinx.fem.Expression(lmbda, points),
            dLambda=(
                dolfinx.fem.Expression(self._rate(lmbda), points)
                if self.scheme == "segregated"
                else None
            ),
            tension_kPa=dolfinx.fem.Expression(tension * (self._to_Pa / 1000.0), points),
            outputs={
                name: dolfinx.fem.Expression(provided[index], points)
                for name, index in self.module.provides.items()
            },
        )

    def Fe(self, F: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        return F

    def strain_energy(self, C: ufl.core.expr.Expr):
        """Not available for this backend (ADR 0003).

        ``Ta`` depends on the stretch through states that depend on the stretch
        *rate*, so there is no closed-form potential to differentiate. ``S`` is
        supplied directly, which is all ``pulse.StaticProblem`` assembles.
        """
        raise NotImplementedError(
            "GeneratedActivation has no active strain-energy potential; it supplies S "
            "directly. pulse.StaticProblem assembles model.S(C), so this is not needed.",
        )

    def S(self, C: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        """Active second Piola-Kirchhoff stress, in Pa, after one step at the stretch of ``C``."""
        lmbda = self._fibre_stretch(C)
        new, p = self._step(lmbda)
        Ta = self.module.monitor_values(self.t, new, p, self._missing)[self._tension_index]
        if self.tension_scale is not None:
            Ta = self.tension_scale * Ta
        Ta_Pa = self._to_Pa * Ta
        if self.formulation == pulse.ActiveStressFormulation.stretch:
            Ta_Pa = Ta_Pa / lmbda
        return Ta_Pa * ufl.outer(self.f0, self.f0)

    def P(self, F: ufl.core.expr.Expr) -> ufl.core.expr.Expr:
        return F * self.S(F.T * F)

    # ------------------------------------------------------------------
    # After a converged solve
    # ------------------------------------------------------------------

    def post_solve(self) -> None:
        """Accept the step taken with the converged displacement.

        Stores the states of the step the residual used, and λ(u), as the new
        previous values; for ``segregated`` also refreshes the frozen ``lmbda`` and
        ``dLambda``; refreshes ``outputs`` and ``active_tension``.

        Everything is evaluated before anything is overwritten: the step reads
        ``states_prev``, and ``lmbda_prev`` (monolithic) or the frozen pair
        (segregated).
        """
        expressions = self._post_solve_expressions
        if expressions is None:
            raise RuntimeError("register(u) must be called before post_solve()")

        self._states_next.interpolate(expressions.states)
        self.outputs["lmbda"].interpolate(expressions.lmbda)
        if expressions.dLambda is not None:
            self._dLambda_next.interpolate(expressions.dLambda)
        self._tension_kPa.interpolate(expressions.tension_kPa)
        for name, expression in expressions.outputs.items():
            self.outputs[name].interpolate(expression)

        lmbda = self.outputs["lmbda"].x.array
        self.states_prev.x.array[:] = self._states_next.x.array
        self.lmbda_prev.x.array[:] = lmbda
        if self.scheme == "segregated":
            self._lmbda_frozen.x.array[:] = lmbda
            self._dLambda_frozen.x.array[:] = self._dLambda_next.x.array

        self._average_tension()
