"""GeneratedActivation: the generated contraction model as a pulse active model.

The backend is driven here without pulse: a displacement ``u`` is prescribed so
that the fibre stretch is known exactly, the backend is handed ``u`` through
``register``, and each step is taken by setting ``t``, ``dt`` and the EP inputs
and calling ``post_solve()`` -- which is what the controller will do after each
converged mechanics solve.

The reference is the *same* ``mechanics`` component generated by gotranx's
numpy printer instead of its UFL printer, so the two runs differ only in how the
expressions are evaluated.
"""

import types
from functools import cache
from pathlib import Path

from mpi4py import MPI

import basix.ufl
import dolfinx
import gotranx
import numpy as np
import pulse
import pytest
import ufl
from conftest import calcium

from simcardemsx.averaging import make_averager
from simcardemsx.backends import GeneratedActivation

ODEFILES_DIR = Path(__file__).parent.parent / "numerical_experiments" / "odefiles"


@cache
def _numpy_mech(split: str) -> types.ModuleType:
    """The ``mechanics`` component of ``split``, generated as numpy (GRL) and loaded.

    Generated exactly as :func:`simcardemsx.ode_model.generate_ode_code` generates
    the UFL module -- same component, same scheme, same ``missing_values`` -- but
    with ``gotran2py``.
    """
    ode = gotranx.load_ode(ODEFILES_DIR / f"ToRORd_dynCl_endo_{split}.ode")
    mechanics_comp = ode.get_component("mechanics")
    ep_ode = ode - mechanics_comp
    code = gotranx.cli.gotran2py.get_code(
        mechanics_comp.to_ode(),
        scheme=[gotranx.schemes.Scheme.generalized_rush_larsen],
        missing_values=ep_ode.missing_variables,
    )
    module = types.ModuleType(f"numpy_mechanics_{split}")
    exec(code, module.__dict__)
    return module


def _mesh() -> dolfinx.mesh.Mesh:
    return dolfinx.mesh.create_unit_cube(MPI.COMM_WORLD, 1, 1, 1)


def _f0(mesh):
    return dolfinx.fem.Constant(mesh, np.array([1.0, 0.0, 0.0]))


def _set_stretch(u: dolfinx.fem.Function, stretch: float) -> None:
    """Set ``u = ((stretch - 1) x, 0, 0)`` in place, so that ``F = diag(stretch, 1, 1)``."""
    u.interpolate(
        lambda x: np.vstack([(stretch - 1.0) * x[0], np.zeros_like(x[1]), np.zeros_like(x[2])]),
    )


def _prescribed(mesh, stretch: float) -> dolfinx.fem.Function:
    """A P2 displacement whose fibre stretch is exactly ``stretch`` everywhere."""
    u = dolfinx.fem.Function(dolfinx.fem.functionspace(mesh, ("P", 2, (3,))))
    _set_stretch(u, stretch)
    return u


def _S_ff(backend, u) -> dolfinx.fem.Form:
    """``∫ S(C)[0, 0] dx``, compiled once, at the backend's quadrature degree."""
    mesh = u.function_space.mesh
    F = ufl.grad(u) + ufl.Identity(3)
    dx = ufl.dx(domain=mesh, metadata={"quadrature_degree": backend.quadrature_degree})
    return dolfinx.fem.form(backend.S(F.T * F)[0, 0] * dx)


def _states(backend, mech) -> np.ndarray:
    """``states_prev`` as an array of shape (points, states)."""
    return backend.states_prev.x.array.reshape(-1, len(mech.state))


def _activated(backend, mech) -> None:
    """Put some cross-bridges in the attached states, so that ``Ta`` is nonzero.

    From the initial state no cross-bridges are attached and one step leaves them
    that way, so ``Ta`` would be zero whatever ``dt`` or the stretch rate.
    """
    _states(backend, mech)[:, mech.state["XS"]] = 0.1
    _states(backend, mech)[:, mech.state["XW"]] = 0.1


def test_isometric_clamp_matches_numpy(split_modules):
    """Gate: at λ ≡ 1 the backend's GRL step is the numpy GRL step, to round-off."""
    _, mech = split_modules["caisplit"]
    ref = _numpy_mech("caisplit")
    mesh = _mesh()
    u = _prescribed(mesh, 1.0)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(u)

    dt = 0.5
    states = ref.init_state_values()
    params = ref.init_parameter_values(lmbda=1.0, dLambda=0.0)
    Ta_backend, Ta_numpy = [], []
    for n in range(120):
        t_n, t_next = n * dt, (n + 1) * dt
        missing = np.array([calcium(t_next)])

        backend.t.value = t_n
        backend.dt.value = dt
        backend.inputs["cai"].x.array[:] = missing[0]
        backend.post_solve()
        Ta_backend.append(backend.active_tension.x.array.copy())

        states = ref.generalized_rush_larsen(states, t_n, dt, params, missing)
        Ta_numpy.append(ref.monitor_values(t_n, states, params, missing)[ref.monitor["Ta"]])

    Ta_backend_arr = np.array(Ta_backend)
    Ta_numpy_arr = np.broadcast_to(np.array(Ta_numpy)[:, None], Ta_backend_arr.shape)
    # The comparison means nothing unless the clamp actually activates.
    assert Ta_numpy_arr.max() > 1.0  # kPa
    np.testing.assert_allclose(Ta_backend_arr, Ta_numpy_arr, rtol=1e-10, atol=1e-12)


def test_faster_shortening_gives_less_tension(split_modules):
    """Gate: same λ, same time, same calcium -- only the shortening velocity differs.

    The stretch rate enters through ``dLambda`` in the distortion states, so a
    faster ramp to the same final stretch must leave less tension.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    dt, t_end = 0.1, 60.0

    def stretch(t: float, T_r: float) -> float:
        t_start = t_end - T_r
        if t <= t_start:
            return 1.0
        return 1.0 - 0.02 * (t - t_start) / T_r

    Ta_end = []
    for T_r in (20.0, 5.0, 1.0):
        u = _prescribed(mesh, 1.0)
        backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
        backend.register(u)
        for n in range(round(t_end / dt)):
            t_n, t_next = n * dt, (n + 1) * dt
            backend.t.value = t_n
            backend.dt.value = dt
            backend.inputs["cai"].x.array[:] = calcium(t_next)
            _set_stretch(u, stretch(t_next, T_r))
            backend.post_solve()
        np.testing.assert_allclose(backend.outputs["lmbda"].x.array, 0.98, rtol=1e-12)
        Ta_end.append(float(backend.active_tension.x.array.mean()))

    assert Ta_end[0] > Ta_end[1] > Ta_end[2]


def test_form_sees_dt_set_after_construction(split_modules):
    """``dt`` is read when the form is assembled, not when it is compiled.

    The old ``ZetaSplitUFL`` branched on a Python float ``dt`` while building UFL;
    pulse compiles the form once, while ``dt == 0``, so the compiled form never saw
    the stretch rate.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    u = _prescribed(mesh, 0.95)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    _activated(backend, mech)
    backend.inputs["cai"].x.array[:] = 1e-3

    form = _S_ff(backend, u)  # compiled while dt == 0

    backend.dt.value = 0.5
    val_dt05 = dolfinx.fem.assemble_scalar(form)
    backend.dt.value = 1.0
    val_dt1 = dolfinx.fem.assemble_scalar(form)

    assert np.isfinite(val_dt05) and np.isfinite(val_dt1)
    assert val_dt05 != 0.0
    assert not np.isclose(val_dt1, val_dt05)


@pytest.mark.parametrize(
    "formulation, divide_by_lmbda",
    [
        (pulse.ActiveStressFormulation.stretch, True),
        (pulse.ActiveStressFormulation.invariant, False),
    ],
)
def test_S_matches_the_numpy_reference(split_modules, formulation, divide_by_lmbda):
    """Gate: pins the value of ``S``, not just that it changes with ``dt`` (above).

    λ = 0.95 is prescribed exactly (``_prescribed``); ``lmbda_prev`` is left at its
    default 1.0, so dLambda = (0.95 - 1) / dt = -0.1. The form is compiled while
    dt == 0, like ``test_form_sees_dt_set_after_construction``, then assembled after
    dt/t/inputs are set -- so the compiled form must actually see them.

    ``∫ S(C)[0, 0] dx / |Ω|`` is compared against the numpy GRL reference's ``Ta``,
    converted from kPa to Pa (``TENSION_TO_PA["kPa"] == 1000``) and, for the
    ``stretch`` formulation only, divided by λ (ADR 0001).
    """
    _, mech = split_modules["caisplit"]
    ref = _numpy_mech("caisplit")
    mesh = _mesh()
    stretch, dt, cai = 0.95, 0.5, 1e-3

    u = _prescribed(mesh, stretch)
    backend = GeneratedActivation(
        mech,
        mesh,
        _f0(mesh),
        quadrature_degree=2,
        formulation=formulation,
    )
    _activated(backend, mech)
    backend.inputs["cai"].x.array[:] = cai

    form = _S_ff(backend, u)  # compiled while dt == 0
    backend.t.value = 0.0
    backend.dt.value = dt
    S_ff = dolfinx.fem.assemble_scalar(form)
    vol = dolfinx.fem.assemble_scalar(
        dolfinx.fem.form(
            1.0 * ufl.dx(domain=mesh, metadata={"quadrature_degree": backend.quadrature_degree}),
        ),
    )

    y0 = ref.init_state_values()
    y0[ref.state["XS"]] = 0.1
    y0[ref.state["XW"]] = 0.1
    params = ref.init_parameter_values(lmbda=stretch, dLambda=(stretch - 1.0) / dt)
    missing = np.array([cai])
    states = ref.generalized_rush_larsen(y0, 0.0, dt, params, missing)
    Ta_numpy = ref.monitor_values(0.0, states, params, missing)[ref.monitor["Ta"]]

    expected = 1000.0 * Ta_numpy / stretch if divide_by_lmbda else 1000.0 * Ta_numpy
    np.testing.assert_allclose(S_ff / vol, expected, rtol=1e-10)


@pytest.mark.parametrize("scheme", ["monolithic", "segregated", "stabilized"])
def test_solve_before_first_step_is_finite(split_modules, scheme):
    """With ``dt`` left at 0 the step is the identity and ``dLambda`` is 0.

    ``u`` is shortened, so an unguarded ``(λ - lmbda_prev) / dt`` would be -0.05 / 0;
    under ``stabilized`` so would the rate in ``Ka``, the derivative of the step's
    tension with respect to its end stretch.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    u = _prescribed(mesh, 0.95)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme=scheme)
    backend.register(u)

    assert np.isfinite(dolfinx.fem.assemble_scalar(_S_ff(backend, u)))

    backend.post_solve()
    init = np.broadcast_to(mech.init_state_values(), _states(backend, mech).shape)
    np.testing.assert_array_equal(_states(backend, mech), init)
    assert np.all(np.isfinite(backend.active_tension.x.array))


def test_segregated_is_monolithic_lagged_by_one_step(split_modules):
    """``segregated`` steps with the stretch and rate frozen at the last converged step.

    So stretching by ``[0.95, 0.95]`` under ``segregated`` takes the same steps as
    stretching by ``[1.0, 0.95]`` under ``monolithic``: the first step sees λ = 1 and
    dLambda = 0 in both, the second λ = 0.95 and dLambda = -0.05 / dt in both.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    dt = 0.5
    u_seg = _prescribed(mesh, 0.95)
    u_mono = _prescribed(mesh, 1.0)
    seg = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme="segregated")
    mono = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    seg.register(u_seg)
    mono.register(u_mono)

    for n, (stretch_seg, stretch_mono) in enumerate([(0.95, 1.0), (0.95, 0.95)]):
        _set_stretch(u_seg, stretch_seg)
        _set_stretch(u_mono, stretch_mono)
        for backend in (seg, mono):
            if n == 0:
                _activated(backend, mech)
            backend.t.value = n * dt
            backend.dt.value = dt
            backend.inputs["cai"].x.array[:] = 1e-3
            backend.post_solve()

        np.testing.assert_allclose(_states(seg, mech), _states(mono, mech), rtol=1e-12)
        np.testing.assert_allclose(
            seg.active_tension.x.array,
            mono.active_tension.x.array,
            rtol=1e-12,
        )
        # lmbda_prev is λ(u) under both schemes: it is what the next rate is taken from.
        np.testing.assert_allclose(seg.lmbda_prev.x.array, stretch_seg, rtol=1e-12)
    # The rate did change the step, so the equality above is not vacuous.
    assert not np.allclose(_states(seg, mech)[:, mech.state["Zetas"]], 0.0)


def test_unknown_scheme_lists_all_three(split_modules):
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    with pytest.raises(ValueError, match="'monolithic', 'segregated' or 'stabilized'"):
        GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme="staggered")


def test_stabilized_requires_the_stretch_formulation(split_modules):
    """R&Q derive the stabilization term in the stretch formulation, and pulse's
    ``StabilizedActiveStress`` implements only that."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    with pytest.raises(ValueError, match="stretch"):
        GeneratedActivation(
            mech,
            mesh,
            _f0(mesh),
            quadrature_degree=2,
            scheme="stabilized",
            formulation=pulse.ActiveStressFormulation.invariant,
        )


def test_stabilized_is_segregated_plus_the_stiffness_term(split_modules):
    """``stabilized`` is the segregated stress plus ``Ka (λ(u) - λ_n)``, with ``Ka > 0``.

    After one accepted step at λ = 0.95, both schemes freeze the next step's stretch
    at λ_n = 0.95. At λ(u) = λ_n the added term vanishes, so the two stresses agree;
    shortening past λ_n lowers the stabilized stress below the segregated one, and
    lengthening raises it.

    The difference is then pinned exactly, against ``stiffness_kPa``. ``Ka`` is built
    twice, once for the residual (in ``__init__``) and once for ``stiffness_kPa`` (in
    ``register``), and the other gates read only the second. In the stretch
    formulation ``S = (Ta + Ka Δλ) / λ f0⊗f0``, so at the uniform λ = 0.90, with
    ``f0 = e_x``, ``∫ S_stab[0, 0] - ∫ S_seg[0, 0] = ∫ 1000 Ka (0.90 - 0.95) / 0.90``
    (``Ka`` in kPa, ``S`` in Pa).
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    dt = 0.5
    u = _prescribed(mesh, 0.95)
    seg = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme="segregated")
    stab = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme="stabilized")
    for backend in (seg, stab):
        backend.register(u)
        _activated(backend, mech)
        backend.t.value = 0.0
        backend.dt.value = dt
        backend.inputs["cai"].x.array[:] = 1e-3
        backend.post_solve()
        backend.t.value = dt

    form_stab, form_seg = _S_ff(stab, u), _S_ff(seg, u)

    def at(stretch: float):
        _set_stretch(u, stretch)
        return dolfinx.fem.assemble_scalar(form_stab), dolfinx.fem.assemble_scalar(form_seg)

    stab_value, seg_value = at(0.95)  # Δλ = 0
    assert seg_value > 0.0  # the equality below is not vacuous
    np.testing.assert_allclose(stab_value, seg_value, rtol=1e-12)
    stab_short, seg_short = at(0.90)  # shortening: Ka > 0, Δλ < 0
    assert stab_short < seg_short
    stab_value, seg_value = at(1.00)
    assert stab_value > seg_value

    # Accept the step at the u of the 0.90 evaluation. Under ``stabilized``,
    # ``stiffness_kPa`` is evaluated at the frozen point (λ_n = 0.95 and the rate of the
    # first step) whatever u is, from the states the residual stepped from, so it is
    # the Ka of the 0.90 evaluation above.
    _set_stretch(u, 0.90)
    stab.post_solve()
    Ka = stab.stiffness_kPa.x.array
    assert Ka.min() > 0.0  # not vacuous
    dx = ufl.dx(domain=mesh, metadata={"quadrature_degree": stab.quadrature_degree})
    weights = dolfinx.fem.assemble_vector(
        dolfinx.fem.form(ufl.TestFunction(stab.space) * dx),
    ).array
    assert weights.sum() == pytest.approx(1.0, rel=1e-12)  # |Ω| of the unit cube
    expected = float(np.sum(weights * 1000.0 * Ka * (0.90 - 0.95) / 0.90))
    np.testing.assert_allclose(stab_short - seg_short, expected, rtol=1e-12)


def test_outputs_are_missing_values_at_the_new_states(split_modules):
    """``outputs`` carry what EP needs: the module's ``missing_values`` after the step, and λ."""
    _, mech = split_modules["caisplit"]
    ref = _numpy_mech("caisplit")
    mesh = _mesh()
    stretch, dt, cai = 0.97, 0.5, 5e-4
    u = _prescribed(mesh, stretch)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(u)
    backend.dt.value = dt
    backend.inputs["cai"].x.array[:] = cai
    backend.post_solve()

    missing = np.array([cai])
    params = ref.init_parameter_values(lmbda=stretch, dLambda=(stretch - 1.0) / dt)
    states = ref.generalized_rush_larsen(ref.init_state_values(), 0.0, dt, params, missing)
    J_TRPN = ref.missing_values(0.0, states, params, missing)[mech.provides["J_TRPN"]]

    assert set(backend.outputs) == {"J_TRPN", "lmbda"}
    np.testing.assert_allclose(backend.outputs["J_TRPN"].x.array, J_TRPN, rtol=1e-10)
    np.testing.assert_allclose(backend.outputs["lmbda"].x.array, stretch, rtol=1e-12)


@pytest.mark.parametrize("split", ["caisplit", "zetasplit", "catrpnsplit"])
def test_inputs_and_outputs_follow_the_split(split_modules, split):
    _, mech = split_modules[split]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    assert set(backend.inputs) == set(mech.missing)
    assert set(backend.outputs) == set(mech.provides) | {"lmbda"}
    assert backend.states_prev.function_space.value_shape == (len(mech.state),)


def test_dg1_states_take_the_same_step_as_quadrature(split_modules):
    """``element=("DG", 1)`` stores the states elsewhere, but on uniform data steps alike."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    Ta = {}
    for element in (None, ("DG", 1)):
        u = _prescribed(mesh, 0.97)
        backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, element=element)
        backend.register(u)
        _activated(backend, mech)
        backend.dt.value = 0.5
        backend.inputs["cai"].x.array[:] = 1e-3
        backend.post_solve()
        Ta[element] = backend.active_tension.x.array.copy()

    assert np.all(Ta[None] > 0.0)
    np.testing.assert_allclose(Ta[("DG", 1)], Ta[None], rtol=1e-12)


def test_unknown_tension_or_parameter_raises(split_modules):
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    f0 = _f0(mesh)
    with pytest.raises(KeyError, match="Ta"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, tension="Tension")
    with pytest.raises(KeyError, match="Available"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, parameters={"Tref_typo": 1.0})
    # lmbda and dLambda come from the displacement; an override would be ignored.
    with pytest.raises(KeyError, match="displacement"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, parameters={"lmbda": 1.1})
    with pytest.raises(ValueError, match="kPa"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, tension_unit="mmHg")


def test_parameter_override_reaches_the_step(split_modules):
    """``Ta`` is linear in ``Tref``, so halving it halves the tension after a step."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    Ta = {}
    for Tref in (120.0, 60.0):
        u = _prescribed(mesh, 1.0)
        backend = GeneratedActivation(
            mech,
            mesh,
            _f0(mesh),
            quadrature_degree=2,
            parameters={"Tref": Tref},
        )
        assert float(backend.parameters["Tref"].value) == Tref
        backend.register(u)
        _activated(backend, mech)
        backend.dt.value = 0.5
        backend.inputs["cai"].x.array[:] = 1e-3
        backend.post_solve()
        Ta[Tref] = backend.active_tension.x.array.copy()

    assert np.all(Ta[120.0] > 0.0)
    np.testing.assert_allclose(Ta[60.0], 0.5 * Ta[120.0], rtol=1e-12)


def test_is_a_pulse_active_model_with_no_potential(split_modules):
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    assert isinstance(backend, pulse.active_model.ActiveModel)
    with pytest.raises(NotImplementedError):
        backend.strain_energy(ufl.Identity(3))


def test_tension_kPa_is_the_function_post_solve_writes(split_modules):
    """``tension_kPa`` is the backend's own quadrature tension, which ``post_solve``
    writes in place and ``active_tension`` is averaged from: not a copy."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(_prescribed(mesh, 1.0))
    tension = backend.tension_kPa
    assert tension.function_space is backend.space

    _activated(backend, mech)
    backend.dt.value = 0.5
    backend.inputs["cai"].x.array[:] = 1e-3
    backend.post_solve()

    assert backend.tension_kPa is tension
    assert tension.x.array.min() > 0.0
    averaged = dolfinx.fem.Function(backend.active_tension.function_space)
    make_averager(tension, averaged)()
    np.testing.assert_array_equal(averaged.x.array, backend.active_tension.x.array)
    with pytest.raises(AttributeError):
        backend.tension_kPa = tension


@pytest.mark.parametrize("scheme", ["monolithic", "segregated", "stabilized"])
@pytest.mark.parametrize("dt", [2.0, 0.05])
@pytest.mark.parametrize("s1, s2", [(0.95, 0.93), (0.85, 0.83)])
def test_stiffness_is_the_derivative_of_the_stepped_tension(split_modules, scheme, dt, s1, s2):
    """``stiffness_kPa`` is Land's closed-form ``dTa/dλ`` of the step, at the scheme's point.

    The evaluation point is λ(u) for ``monolithic`` and the frozen λ_n (here ``s1``)
    for the other two. The two stretch pairs lie either side of 0.87, so both branches
    of the length dependence's slope are exercised.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    u = _prescribed(mesh, s1)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme=scheme)
    backend.register(u)
    _activated(backend, mech)
    backend.inputs["cai"].x.array[:] = 1e-3
    backend.t.value = 0.0
    backend.dt.value = dt
    backend.post_solve()
    _set_stretch(u, s2)
    backend.t.value = dt
    backend.post_solve()

    lmbda_e = s2 if scheme == "monolithic" else s1
    kuw, kws, phi, rw, rs, Tot_A, Beta0, Tref = (
        backend.parameters[k].value
        for k in ("kuw", "kws", "phi", "rw", "rs", "Tot_A", "Beta0", "Tref")
    )
    states = _states(backend, mech)
    XS, XW = states[:, mech.state["XS"]], states[:, mech.state["XW"]]
    Zetas, Zetaw = states[:, mech.state["Zetas"]], states[:, mech.state["Zetaw"]]

    cw = kuw * phi * (1 - rw) / rw
    cs = kws * phi * rw * (1 - rs) / rs
    A = Tot_A * rs / (rs + rw * (1 - rs))

    def kappa(c):
        return (1 - np.exp(-c * dt)) / (c * dt)

    l12 = min(lmbda_e, 1.2)
    hp = 1 + Beta0 * (l12 + min(l12, 0.87) - 1.87)
    h = max(hp, 0)
    dh = Beta0 * ((lmbda_e < 1.2) + (l12 < 0.87)) if hp > 0 else 0
    rate = h * Tref / rs * (A * kappa(cs) * XS + A * kappa(cw) * XW)
    length = dh * Tref / rs * (XS * (1 + Zetas) + XW * Zetaw)
    assert rate.min() > 0  # the check is not vacuous
    # Round-off is measured against the size of the two terms, not of their sum. Where
    # shortening drives the length path negative they cancel: at (0.85, 0.83), dt 0.05,
    # monolithic, Ka = -13.6 kPa is +470 kPa of rate and -483 kPa of length, so a
    # discrepancy of a few ulp in the terms is 1e-12 of the sum (seen on dolfinx nightly).
    terms = np.abs(rate) + np.abs(length)
    np.testing.assert_array_less(
        np.abs(backend.stiffness_kPa.x.array - (rate + length)),
        1e-12 * terms,
    )


def test_stiffness_at_rest_is_the_length_path(split_modules):
    """At ``dt == 0`` and λ = 1 the rate path is gone: ``Ka = Beta0 Tref XS / rs``."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme="stabilized")
    backend.register(_prescribed(mesh, 1.0))
    _activated(backend, mech)
    backend.dt.value = 0.0
    backend.post_solve()

    Beta0, Tref, rs = (backend.parameters[k].value for k in ("Beta0", "Tref", "rs"))
    expected = Beta0 * Tref / rs * 0.1
    assert expected > 0.0
    np.testing.assert_allclose(backend.stiffness_kPa.x.array, expected, rtol=1e-12)


def test_stiffness_kPa_is_the_function_post_solve_writes(split_modules):
    """``stiffness_kPa`` is the backend's own quadrature ``Function``, written in place."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(_prescribed(mesh, 1.0))
    stiffness = backend.stiffness_kPa
    assert stiffness.function_space is backend.space

    _activated(backend, mech)
    backend.dt.value = 0.5
    backend.inputs["cai"].x.array[:] = 1e-3
    backend.post_solve()

    assert backend.stiffness_kPa is stiffness
    assert stiffness.x.array.min() > 0.0
    with pytest.raises(AttributeError):
        backend.stiffness_kPa = stiffness


def _two_tet_mesh() -> dolfinx.mesh.Mesh:
    """Two tetrahedra sharing the face (1,0,0)-(0,1,0)-(0,0,1).

    One is the reference tet, with the exclusive vertex (0, 0, 0); the other shares
    that face and has the exclusive vertex (1, 1, 1). Which of them is local cell 0
    is dolfinx's choice (nightly reorders them), so find a cell's own exclusive
    vertex with :func:`_exclusive_vertex`, never by assuming the input order.
    """
    x = np.array(
        [
            [0.0, 0.0, 0.0],
            [1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 1.0, 1.0],
        ],
    )
    cells = np.array([[0, 1, 2, 3], [1, 2, 3, 4]], dtype=np.int64)
    element = basix.ufl.element("Lagrange", "tetrahedron", 1, shape=(3,))
    return dolfinx.mesh.create_mesh(MPI.COMM_WORLD, cells, ufl.Mesh(element), x)


def _exclusive_vertex(mesh: dolfinx.mesh.Mesh, cell: int) -> np.ndarray:
    """The coordinates of the one vertex of local ``cell`` that the other cell lacks."""
    x = mesh.geometry.x
    dofmap = mesh.geometry.dofmap
    own = {tuple(x[i]) for i in dofmap[cell]}
    other = {tuple(x[i]) for i in dofmap[1 - cell]}
    (vertex,) = own - other
    return np.array(vertex)


def test_tension_scale_zeroes_the_masked_cell(split_modules):
    """``tension_scale`` multiplies ``Ta`` in both ``S`` and ``active_tension``, and
    nothing else.

    A DG0 mask, 0 on cell 0 and 1 (a no-op) on cell 1, is compared against an
    otherwise identical backend with no ``tension_scale`` at all, driven by the
    same Ca_i split and inputs: cell 0's active stress and tension must vanish
    exactly; cell 1's must be untouched; and every output, i.e. everything that
    crosses back to EP, must be the unmasked backend's on both cells.
    """
    _, mech = split_modules["caisplit"]
    mesh = _two_tet_mesh()
    f0 = _f0(mesh)
    quadrature_degree = 2

    V_dg0 = dolfinx.fem.functionspace(mesh, ("DG", 0))
    tension_scale = dolfinx.fem.Function(V_dg0)
    tension_scale.x.array[V_dg0.dofmap.cell_dofs(0)[0]] = 0.0
    tension_scale.x.array[V_dg0.dofmap.cell_dofs(1)[0]] = 1.0

    u = dolfinx.fem.Function(dolfinx.fem.functionspace(mesh, ("P", 2, (3,))))
    masked = GeneratedActivation(
        mech,
        mesh,
        f0,
        quadrature_degree=quadrature_degree,
        tension_scale=tension_scale,
    )
    unmasked = GeneratedActivation(mech, mesh, f0, quadrature_degree=quadrature_degree)
    masked.register(u)
    unmasked.register(u)

    for n in range(30):
        for backend in (masked, unmasked):
            backend.t.value = float(n)
            backend.dt.value = 1.0
            backend.inputs["cai"].x.array[:] = 1e-3
            backend.post_solve()

    # The comparison means nothing unless the unmasked backend actually activated.
    assert unmasked.active_tension.x.array.max() > 1.0  # kPa

    F = ufl.grad(u) + ufl.Identity(3)
    C = F.T * F
    points = masked.space.element.interpolation_points
    cells = np.array([0, 1], dtype=np.int32)
    S_masked = dolfinx.fem.Expression(masked.S(C), points).eval(mesh, cells)
    S_unmasked = dolfinx.fem.Expression(unmasked.S(C), points).eval(mesh, cells)

    np.testing.assert_array_equal(S_masked[0], 0.0)
    cell0_dofs = masked.space.dofmap.cell_dofs(0)
    cell1_dofs = masked.space.dofmap.cell_dofs(1)
    assert unmasked.stiffness_kPa.x.array[cell0_dofs].min() > 0.0  # not vacuous
    np.testing.assert_array_equal(masked.stiffness_kPa.x.array[cell0_dofs], 0.0)
    np.testing.assert_allclose(
        masked.stiffness_kPa.x.array[cell1_dofs],
        unmasked.stiffness_kPa.x.array[cell1_dofs],
        rtol=1e-12,
    )
    np.testing.assert_allclose(S_masked[1], S_unmasked[1], rtol=1e-12)

    V_p1 = masked.active_tension.function_space
    coords = V_p1.tabulate_dof_coordinates()
    vertex0, vertex1 = _exclusive_vertex(mesh, 0), _exclusive_vertex(mesh, 1)
    dof_cell0_exclusive = int(np.argmin(np.linalg.norm(coords - vertex0, axis=1)))
    dof_cell1_exclusive = int(np.argmin(np.linalg.norm(coords - vertex1, axis=1)))

    assert masked.active_tension.x.array[dof_cell0_exclusive] == 0.0
    np.testing.assert_allclose(
        masked.active_tension.x.array[dof_cell1_exclusive],
        unmasked.active_tension.x.array[dof_cell1_exclusive],
        rtol=1e-12,
    )

    # What crosses back to EP is not scaled: the masked cell keeps its cellular
    # dynamics. That means nothing unless the masked cell has something to lose.
    cell0 = masked.space.dofmap.cell_dofs(0)
    assert set(masked.outputs) == set(unmasked.outputs) == {*mech.provides, "lmbda"}
    for name in mech.provides:
        assert np.all(unmasked.outputs[name].x.array[cell0] != 0.0), name
    for name in unmasked.outputs:
        np.testing.assert_array_equal(
            masked.outputs[name].x.array,
            unmasked.outputs[name].x.array,
            err_msg=name,
        )


def test_tension_scale_masks_the_stabilization_term(split_modules):
    """``tension_scale`` multiplies ``Ka`` as well as ``Ta`` under ``stabilized``.

    The set-up of :func:`test_stabilized_is_segregated_plus_the_stiffness_term`
    (which shows ``Ka > 0`` there), on two tets with the DG0 mask of
    :func:`test_tension_scale_zeroes_the_masked_cell`. ``S`` is assembled at a
    stretch other than the frozen one, so ``Ka (λ(u) - λ_n)`` is nonzero: were only
    ``Ta`` masked, the masked cell would still carry it.
    """
    _, mech = split_modules["caisplit"]
    mesh = _two_tet_mesh()
    dt = 0.5

    V_dg0 = dolfinx.fem.functionspace(mesh, ("DG", 0))
    tension_scale = dolfinx.fem.Function(V_dg0)
    tension_scale.x.array[V_dg0.dofmap.cell_dofs(0)[0]] = 0.0
    tension_scale.x.array[V_dg0.dofmap.cell_dofs(1)[0]] = 1.0

    u = _prescribed(mesh, 0.95)
    backend = GeneratedActivation(
        mech,
        mesh,
        _f0(mesh),
        quadrature_degree=2,
        scheme="stabilized",
        tension_scale=tension_scale,
    )
    backend.register(u)
    _activated(backend, mech)
    backend.dt.value = dt
    backend.inputs["cai"].x.array[:] = 1e-3
    backend.post_solve()
    backend.t.value = dt

    _set_stretch(u, 0.90)  # Δλ = -0.05
    F = ufl.grad(u) + ufl.Identity(3)
    dx = ufl.dx(domain=mesh, metadata={"quadrature_degree": backend.quadrature_degree})
    S_ff = dolfinx.fem.assemble_vector(
        dolfinx.fem.form(backend.S(F.T * F)[0, 0] * ufl.TestFunction(V_dg0) * dx),
    ).array
    masked, unmasked = (S_ff[V_dg0.dofmap.cell_dofs(cell)[0]] for cell in (0, 1))

    np.testing.assert_allclose(masked, 0.0, atol=0)
    assert unmasked != 0.0


_REST_DT = 0.5


def _rest_backends(mech, mesh, u, *, reset):
    """One activated backend per scheme, registered on ``u``, after one accepted step.

    The step is taken at λ = 1 by the monolithic scheme and at λ = 0.95 by the frozen
    ones. Both steps are the same step (the frozen schemes advance at the frozen
    λ = 1, rate 0: segregated is monolithic lagged by one step), so the states agree
    between the schemes and have moved from where they started, and the frozen schemes
    leave it with a frozen rate of (0.95 - 1) / dt, not 0.

    ``u`` is then set to λ = 0.9 and, if ``reset``, ``reset_stretch()`` is called. Returns
    the backends, ready for a second step of dt 0.5, and a copy of each one's
    ``states_prev`` from just before the reset.
    """
    backends = {}
    for scheme in ("monolithic", "segregated", "stabilized"):
        backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme=scheme)
        backend.register(u)
        _activated(backend, mech)
        backend.t.value = 0.0
        backend.dt.value = _REST_DT
        backend.inputs["cai"].x.array[:] = 1e-3
        _set_stretch(u, 1.0 if scheme == "monolithic" else 0.95)
        backend.post_solve()
        backends[scheme] = backend

    _set_stretch(u, 0.9)
    before = {}
    for scheme, backend in backends.items():
        before[scheme] = backend.states_prev.x.array.copy()
        if reset:
            backend.reset_stretch()
        backend.t.value = _REST_DT
    return backends, before


def test_reset_stretch_makes_the_schemes_agree_at_rest(split_modules):
    """A problem that starts deformed at λ = 0.9 is at rest there, whatever the scheme.

    ``reset_stretch`` seeds ``lmbda_prev``, the frozen pair and ``outputs["lmbda"]``, so
    the next step sees a stretch rate of 0 under every scheme, and it keeps the states.
    It is called after a step that left the frozen schemes a nonzero frozen rate, so
    each of those is checked on values it has to change (or keep). Without the reset
    the frozen schemes step from λ = 0.95 at that rate and differ from the monolithic
    one.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    u = _prescribed(mesh, 1.0)

    # Not vacuous: before the reset the frozen schemes carry a nonzero frozen rate, and
    # the step moved the states.
    fresh, _ = _rest_backends(mech, mesh, u, reset=False)
    initial = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    _activated(initial, mech)
    for scheme in ("segregated", "stabilized"):
        np.testing.assert_allclose(fresh[scheme]._dLambda_frozen.x.array, -0.05 / _REST_DT)
    for backend in fresh.values():
        assert not np.allclose(backend.states_prev.x.array, initial.states_prev.x.array)

    reset, before = _rest_backends(mech, mesh, u, reset=True)
    for scheme, backend in reset.items():
        np.testing.assert_array_equal(backend._dLambda_frozen.x.array, 0.0)
        np.testing.assert_array_equal(backend.states_prev.x.array, before[scheme])
        lmbda = backend.outputs["lmbda"].x.array
        np.testing.assert_allclose(lmbda, 0.9, rtol=1e-12)
        np.testing.assert_array_equal(backend.lmbda_prev.x.array, lmbda)
        np.testing.assert_array_equal(backend._lmbda_frozen.x.array, lmbda)
    S = {name: dolfinx.fem.assemble_scalar(_S_ff(b, u)) for name, b in reset.items()}
    assert S["monolithic"] > 0.0
    np.testing.assert_allclose(S["segregated"], S["monolithic"], rtol=1e-12)
    np.testing.assert_allclose(S["stabilized"], S["monolithic"], rtol=1e-12)

    # Not vacuous: without the reset the segregated scheme steps from λ = 0.95.
    S_fresh = dolfinx.fem.assemble_scalar(_S_ff(fresh["segregated"], u))
    assert not np.isclose(S_fresh, S["monolithic"], rtol=1e-6)


def test_reset_stretch_before_register_raises(split_modules):
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    with pytest.raises(RuntimeError, match="register"):
        backend.reset_stretch()
