"""GeneratedActivation: the generated contraction model as a pulse active model.

The backend is driven here without pulse: a displacement ``u`` is prescribed so
that the fibre stretch is known exactly, the backend is handed ``u`` through
``register``, and each step is taken by setting ``t``, ``dt`` and the EP inputs
and calling ``post_solve()`` -- which is what the controller will do after each
converged mechanics solve.

The reference is the *same* ``mechanics`` component generated by gotranx's
numpy printer instead of its UFL printer, so the two runs differ only in how the
expressions are evaluated.
"""

import types
from functools import cache
from pathlib import Path

from mpi4py import MPI

import dolfinx
import gotranx
import numpy as np
import pulse
import pytest
import ufl
from conftest import calcium

from simcardemsx.backends import GeneratedActivation

ODEFILES_DIR = Path(__file__).parent.parent / "numerical_experiments" / "odefiles"


@cache
def _numpy_mech(split: str) -> types.ModuleType:
    """The ``mechanics`` component of ``split``, generated as numpy (GRL) and loaded.

    Generated exactly as :func:`simcardemsx.ode_model.generate_ode_code` generates
    the UFL module -- same component, same scheme, same ``missing_values`` -- but
    with ``gotran2py``.
    """
    ode = gotranx.load_ode(ODEFILES_DIR / f"ToRORd_dynCl_endo_{split}.ode")
    mechanics_comp = ode.get_component("mechanics")
    ep_ode = ode - mechanics_comp
    code = gotranx.cli.gotran2py.get_code(
        mechanics_comp.to_ode(),
        scheme=[gotranx.schemes.Scheme.generalized_rush_larsen],
        missing_values=ep_ode.missing_variables,
    )
    module = types.ModuleType(f"numpy_mechanics_{split}")
    exec(code, module.__dict__)
    return module


def _mesh() -> dolfinx.mesh.Mesh:
    return dolfinx.mesh.create_unit_cube(MPI.COMM_WORLD, 1, 1, 1)


def _f0(mesh):
    return dolfinx.fem.Constant(mesh, np.array([1.0, 0.0, 0.0]))


def _set_stretch(u: dolfinx.fem.Function, stretch: float) -> None:
    """Set ``u = ((stretch - 1) x, 0, 0)`` in place, so that ``F = diag(stretch, 1, 1)``."""
    u.interpolate(
        lambda x: np.vstack([(stretch - 1.0) * x[0], np.zeros_like(x[1]), np.zeros_like(x[2])]),
    )


def _prescribed(mesh, stretch: float) -> dolfinx.fem.Function:
    """A P2 displacement whose fibre stretch is exactly ``stretch`` everywhere."""
    u = dolfinx.fem.Function(dolfinx.fem.functionspace(mesh, ("P", 2, (3,))))
    _set_stretch(u, stretch)
    return u


def _S_ff(backend, u) -> dolfinx.fem.Form:
    """``∫ S(C)[0, 0] dx``, compiled once, at the backend's quadrature degree."""
    mesh = u.function_space.mesh
    F = ufl.grad(u) + ufl.Identity(3)
    dx = ufl.dx(domain=mesh, metadata={"quadrature_degree": backend.quadrature_degree})
    return dolfinx.fem.form(backend.S(F.T * F)[0, 0] * dx)


def _states(backend, mech) -> np.ndarray:
    """``states_prev`` as an array of shape (points, states)."""
    return backend.states_prev.x.array.reshape(-1, len(mech.state))


def _activated(backend, mech) -> None:
    """Put some cross-bridges in the attached states, so that ``Ta`` is nonzero.

    From the initial state no cross-bridges are attached and one step leaves them
    that way, so ``Ta`` would be zero whatever ``dt`` or the stretch rate.
    """
    _states(backend, mech)[:, mech.state["XS"]] = 0.1
    _states(backend, mech)[:, mech.state["XW"]] = 0.1


def test_isometric_clamp_matches_numpy(split_modules):
    """Gate: at λ ≡ 1 the backend's GRL step is the numpy GRL step, to round-off."""
    _, mech = split_modules["caisplit"]
    ref = _numpy_mech("caisplit")
    mesh = _mesh()
    u = _prescribed(mesh, 1.0)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(u)

    dt = 0.5
    states = ref.init_state_values()
    params = ref.init_parameter_values(lmbda=1.0, dLambda=0.0)
    Ta_backend, Ta_numpy = [], []
    for n in range(120):
        t_n, t_next = n * dt, (n + 1) * dt
        missing = np.array([calcium(t_next)])

        backend.t.value = t_n
        backend.dt.value = dt
        backend.inputs["cai"].x.array[:] = missing[0]
        backend.post_solve()
        Ta_backend.append(backend.active_tension.x.array.copy())

        states = ref.generalized_rush_larsen(states, t_n, dt, params, missing)
        Ta_numpy.append(ref.monitor_values(t_n, states, params, missing)[ref.monitor["Ta"]])

    Ta_backend_arr = np.array(Ta_backend)
    Ta_numpy_arr = np.broadcast_to(np.array(Ta_numpy)[:, None], Ta_backend_arr.shape)
    # The comparison means nothing unless the clamp actually activates.
    assert Ta_numpy_arr.max() > 1.0  # kPa
    np.testing.assert_allclose(Ta_backend_arr, Ta_numpy_arr, rtol=1e-10, atol=1e-12)


def test_faster_shortening_gives_less_tension(split_modules):
    """Gate: same λ, same time, same calcium -- only the shortening velocity differs.

    The stretch rate enters through ``dLambda`` in the distortion states, so a
    faster ramp to the same final stretch must leave less tension.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    dt, t_end = 0.1, 60.0

    def stretch(t: float, T_r: float) -> float:
        t_start = t_end - T_r
        if t <= t_start:
            return 1.0
        return 1.0 - 0.02 * (t - t_start) / T_r

    Ta_end = []
    for T_r in (20.0, 5.0, 1.0):
        u = _prescribed(mesh, 1.0)
        backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
        backend.register(u)
        for n in range(round(t_end / dt)):
            t_n, t_next = n * dt, (n + 1) * dt
            backend.t.value = t_n
            backend.dt.value = dt
            backend.inputs["cai"].x.array[:] = calcium(t_next)
            _set_stretch(u, stretch(t_next, T_r))
            backend.post_solve()
        np.testing.assert_allclose(backend.outputs["lmbda"].x.array, 0.98, rtol=1e-12)
        Ta_end.append(float(backend.active_tension.x.array.mean()))

    assert Ta_end[0] > Ta_end[1] > Ta_end[2]


def test_form_sees_dt_set_after_construction(split_modules):
    """``dt`` is read when the form is assembled, not when it is compiled.

    The old ``ZetaSplitUFL`` branched on a Python float ``dt`` while building UFL;
    pulse compiles the form once, while ``dt == 0``, so the compiled form never saw
    the stretch rate.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    u = _prescribed(mesh, 0.95)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    _activated(backend, mech)
    backend.inputs["cai"].x.array[:] = 1e-3

    form = _S_ff(backend, u)  # compiled while dt == 0

    backend.dt.value = 0.5
    val_dt05 = dolfinx.fem.assemble_scalar(form)
    backend.dt.value = 1.0
    val_dt1 = dolfinx.fem.assemble_scalar(form)

    assert np.isfinite(val_dt05) and np.isfinite(val_dt1)
    assert val_dt05 != 0.0
    assert not np.isclose(val_dt1, val_dt05)


@pytest.mark.parametrize(
    "formulation, divide_by_lmbda",
    [
        (pulse.ActiveStressFormulation.stretch, True),
        (pulse.ActiveStressFormulation.invariant, False),
    ],
)
def test_S_matches_the_numpy_reference(split_modules, formulation, divide_by_lmbda):
    """Gate: pins the value of ``S``, not just that it changes with ``dt`` (above).

    λ = 0.95 is prescribed exactly (``_prescribed``); ``lmbda_prev`` is left at its
    default 1.0, so dLambda = (0.95 - 1) / dt = -0.1. The form is compiled while
    dt == 0, like ``test_form_sees_dt_set_after_construction``, then assembled after
    dt/t/inputs are set -- so the compiled form must actually see them.

    ``∫ S(C)[0, 0] dx / |Ω|`` is compared against the numpy GRL reference's ``Ta``,
    converted from kPa to Pa (``TENSION_TO_PA["kPa"] == 1000``) and, for the
    ``stretch`` formulation only, divided by λ (ADR 0001).
    """
    _, mech = split_modules["caisplit"]
    ref = _numpy_mech("caisplit")
    mesh = _mesh()
    stretch, dt, cai = 0.95, 0.5, 1e-3

    u = _prescribed(mesh, stretch)
    backend = GeneratedActivation(
        mech,
        mesh,
        _f0(mesh),
        quadrature_degree=2,
        formulation=formulation,
    )
    _activated(backend, mech)
    backend.inputs["cai"].x.array[:] = cai

    form = _S_ff(backend, u)  # compiled while dt == 0
    backend.t.value = 0.0
    backend.dt.value = dt
    S_ff = dolfinx.fem.assemble_scalar(form)
    vol = dolfinx.fem.assemble_scalar(
        dolfinx.fem.form(
            1.0 * ufl.dx(domain=mesh, metadata={"quadrature_degree": backend.quadrature_degree}),
        ),
    )

    y0 = ref.init_state_values()
    y0[ref.state["XS"]] = 0.1
    y0[ref.state["XW"]] = 0.1
    params = ref.init_parameter_values(lmbda=stretch, dLambda=(stretch - 1.0) / dt)
    missing = np.array([cai])
    states = ref.generalized_rush_larsen(y0, 0.0, dt, params, missing)
    Ta_numpy = ref.monitor_values(0.0, states, params, missing)[ref.monitor["Ta"]]

    expected = 1000.0 * Ta_numpy / stretch if divide_by_lmbda else 1000.0 * Ta_numpy
    np.testing.assert_allclose(S_ff / vol, expected, rtol=1e-10)


def test_solve_before_first_step_is_finite(split_modules):
    """With ``dt`` left at 0 the step is the identity and ``dLambda`` is 0.

    ``u`` is shortened, so an unguarded ``(λ - lmbda_prev) / dt`` would be -0.05 / 0.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    u = _prescribed(mesh, 0.95)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(u)

    assert np.isfinite(dolfinx.fem.assemble_scalar(_S_ff(backend, u)))

    backend.post_solve()
    init = np.broadcast_to(mech.init_state_values(), _states(backend, mech).shape)
    np.testing.assert_array_equal(_states(backend, mech), init)
    assert np.all(np.isfinite(backend.active_tension.x.array))


def test_segregated_is_monolithic_lagged_by_one_step(split_modules):
    """``segregated`` steps with the stretch and rate frozen at the last converged step.

    So stretching by ``[0.95, 0.95]`` under ``segregated`` takes the same steps as
    stretching by ``[1.0, 0.95]`` under ``monolithic``: the first step sees λ = 1 and
    dLambda = 0 in both, the second λ = 0.95 and dLambda = -0.05 / dt in both.
    """
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    dt = 0.5
    u_seg = _prescribed(mesh, 0.95)
    u_mono = _prescribed(mesh, 1.0)
    seg = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, scheme="segregated")
    mono = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    seg.register(u_seg)
    mono.register(u_mono)

    for n, (stretch_seg, stretch_mono) in enumerate([(0.95, 1.0), (0.95, 0.95)]):
        _set_stretch(u_seg, stretch_seg)
        _set_stretch(u_mono, stretch_mono)
        for backend in (seg, mono):
            if n == 0:
                _activated(backend, mech)
            backend.t.value = n * dt
            backend.dt.value = dt
            backend.inputs["cai"].x.array[:] = 1e-3
            backend.post_solve()

        np.testing.assert_allclose(_states(seg, mech), _states(mono, mech), rtol=1e-12)
        np.testing.assert_allclose(
            seg.active_tension.x.array,
            mono.active_tension.x.array,
            rtol=1e-12,
        )
        # lmbda_prev is λ(u) under both schemes: it is what the next rate is taken from.
        np.testing.assert_allclose(seg.lmbda_prev.x.array, stretch_seg, rtol=1e-12)
    # The rate did change the step, so the equality above is not vacuous.
    assert not np.allclose(_states(seg, mech)[:, mech.state["Zetas"]], 0.0)


def test_outputs_are_missing_values_at_the_new_states(split_modules):
    """``outputs`` carry what EP needs: the module's ``missing_values`` after the step, and λ."""
    _, mech = split_modules["caisplit"]
    ref = _numpy_mech("caisplit")
    mesh = _mesh()
    stretch, dt, cai = 0.97, 0.5, 5e-4
    u = _prescribed(mesh, stretch)
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    backend.register(u)
    backend.dt.value = dt
    backend.inputs["cai"].x.array[:] = cai
    backend.post_solve()

    missing = np.array([cai])
    params = ref.init_parameter_values(lmbda=stretch, dLambda=(stretch - 1.0) / dt)
    states = ref.generalized_rush_larsen(ref.init_state_values(), 0.0, dt, params, missing)
    J_TRPN = ref.missing_values(0.0, states, params, missing)[mech.provides["J_TRPN"]]

    assert set(backend.outputs) == {"J_TRPN", "lmbda"}
    np.testing.assert_allclose(backend.outputs["J_TRPN"].x.array, J_TRPN, rtol=1e-10)
    np.testing.assert_allclose(backend.outputs["lmbda"].x.array, stretch, rtol=1e-12)


@pytest.mark.parametrize("split", ["caisplit", "zetasplit", "catrpnsplit"])
def test_inputs_and_outputs_follow_the_split(split_modules, split):
    _, mech = split_modules[split]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    assert set(backend.inputs) == set(mech.missing)
    assert set(backend.outputs) == set(mech.provides) | {"lmbda"}
    assert backend.states_prev.function_space.value_shape == (len(mech.state),)


def test_dg1_states_take_the_same_step_as_quadrature(split_modules):
    """``element=("DG", 1)`` stores the states elsewhere, but on uniform data steps alike."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    Ta = {}
    for element in (None, ("DG", 1)):
        u = _prescribed(mesh, 0.97)
        backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2, element=element)
        backend.register(u)
        _activated(backend, mech)
        backend.dt.value = 0.5
        backend.inputs["cai"].x.array[:] = 1e-3
        backend.post_solve()
        Ta[element] = backend.active_tension.x.array.copy()

    assert np.all(Ta[None] > 0.0)
    np.testing.assert_allclose(Ta[("DG", 1)], Ta[None], rtol=1e-12)


def test_unknown_tension_or_parameter_raises(split_modules):
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    f0 = _f0(mesh)
    with pytest.raises(KeyError, match="Ta"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, tension="Tension")
    with pytest.raises(KeyError, match="Available"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, parameters={"Tref_typo": 1.0})
    # lmbda and dLambda come from the displacement; an override would be ignored.
    with pytest.raises(KeyError, match="displacement"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, parameters={"lmbda": 1.1})
    with pytest.raises(ValueError, match="kPa"):
        GeneratedActivation(mech, mesh, f0, quadrature_degree=2, tension_unit="mmHg")


def test_parameter_override_reaches_the_step(split_modules):
    """``Ta`` is linear in ``Tref``, so halving it halves the tension after a step."""
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    Ta = {}
    for Tref in (120.0, 60.0):
        u = _prescribed(mesh, 1.0)
        backend = GeneratedActivation(
            mech,
            mesh,
            _f0(mesh),
            quadrature_degree=2,
            parameters={"Tref": Tref},
        )
        assert float(backend.parameters["Tref"].value) == Tref
        backend.register(u)
        _activated(backend, mech)
        backend.dt.value = 0.5
        backend.inputs["cai"].x.array[:] = 1e-3
        backend.post_solve()
        Ta[Tref] = backend.active_tension.x.array.copy()

    assert np.all(Ta[120.0] > 0.0)
    np.testing.assert_allclose(Ta[60.0], 0.5 * Ta[120.0], rtol=1e-12)


def test_is_a_pulse_active_model_with_no_potential(split_modules):
    _, mech = split_modules["caisplit"]
    mesh = _mesh()
    backend = GeneratedActivation(mech, mesh, _f0(mesh), quadrature_degree=2)
    assert isinstance(backend, pulse.active_model.ActiveModel)
    with pytest.raises(NotImplementedError):
        backend.strain_energy(ufl.Identity(3))
