from pathlib import Path
from types import ModuleType
from typing import NamedTuple

import gotranx

from .utils import load_module_from_path


class ODEModulePaths(NamedTuple):
    """Paths of the two modules written by :func:`generate_ode_code`."""

    ep: Path
    mechanics: Path


class ODEModules(NamedTuple):
    """The two generated modules, loaded.

    Both are needed to set up the coupling: each declares, in its own
    ``missing`` dict, the variables it needs *from the other side*.
    """

    ep: ModuleType
    mechanics: ModuleType


def generate_ode_code(odefile: Path, output_dir: Path) -> ODEModulePaths:
    """
    Pre-processing step: Generates EP and Mechanics Python modules
    from a gotranx ODE file and writes them to the specified directory.

    The mechanics module is generated by gotranx's stock UFL code generator
    (`gotranx.cli.gotran2ufl`): its state update is a UFL expression tree
    rather than numpy, so it can be evaluated symbolically on the mechanics
    mesh by a dolfinx-native activation backend. The EP remainder is still
    generated by the stock numpy generator (`gotranx.cli.gotran2py`) for
    `beat.odesolver.DolfinODESolver`.

    Each module also gets a `provides: dict[str, int]` appended after
    generation: the names its own `missing_values()` returns, by output
    index -- i.e. what it hands to the *other* side. `mechanics.provides`
    is `dict(ep_ode.missing_variables)` and `ep.provides` is
    `dict(mechanics_ode.missing_variables)`.

    Returns the paths of both written modules. Prefer :func:`load_ode_modules`,
    which also loads them -- the mechanics module is not optional, since it is
    the only place that records how many variables the mechanics side needs
    from EP.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    ep_module_file = output_dir / "ep_model.py"
    mechanics_module_file = output_dir / "mechanics_model.py"

    ode = gotranx.load_ode(odefile)
    mechanics_comp = ode.get_component("mechanics")
    mechanics_ode = mechanics_comp.to_ode()
    ep_ode = ode - mechanics_comp

    # Generate Mechanics ODE as UFL
    code_mech = gotranx.cli.gotran2ufl.get_code(
        mechanics_ode,
        scheme=[gotranx.schemes.Scheme.generalized_rush_larsen],
        missing_values=ep_ode.missing_variables,
    )
    code_mech += f"\nprovides = {dict(ep_ode.missing_variables)!r}\n"
    mechanics_module_file.write_text(code_mech)

    # Generate EP ODE
    code_ep = gotranx.cli.gotran2py.get_code(
        ep_ode,
        scheme=[gotranx.schemes.Scheme.generalized_rush_larsen],
        missing_values=mechanics_ode.missing_variables,
    )
    code_ep += f"\nprovides = {dict(mechanics_ode.missing_variables)!r}\n"
    ep_module_file.write_text(code_ep)

    return ODEModulePaths(ep=ep_module_file, mechanics=mechanics_module_file)


def load_ode_modules(odefile: Path, output_dir: Path) -> ODEModules:
    """Generate both ODE modules from ``odefile`` and load them.

    Use this rather than calling :func:`generate_ode_code` and loading only
    ``ep_model``: the split is described jointly by the two modules, and
    :func:`simcardemsx.transfer_plan.resolve` needs both to say what crosses.
    """
    paths = generate_ode_code(odefile, output_dir)
    return ODEModules(
        ep=load_module_from_path("ep_model", paths.ep),
        mechanics=load_module_from_path("mechanics_model", paths.mechanics),
    )
